"""Codegen smoke tests -- Task 7.

Tests cover:
- Each --target cpp --domain X produces a valid file with provenance banner.
- --check mode exits 0 when all committed headers match regen.
- --check mode detects drift when a header is modified.
- examples/use_constants.cpp still compiles and runs after regen.
- per-field enabled flag: ENABLED constants present in C++ header.
"""
from __future__ import annotations
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

SPECGEN_ROOT = Path(__file__).resolve().parent.parent
CODEGEN = SPECGEN_ROOT / "tools" / "codegen.py"
INCLUDE_DIR = SPECGEN_ROOT / "generated" / "cpp"


def run_codegen(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(CODEGEN), *args],
        capture_output=True,
        text=True,
        cwd=str(SPECGEN_ROOT),
    )


# ---------------------------------------------------------------------------
# Emit tests
# ---------------------------------------------------------------------------

def test_packet_cpp_emits_flit_width():
    r = run_codegen("--target", "cpp", "--domain", "packet",
                    "--out", str(INCLUDE_DIR))
    assert r.returncode == 0, r.stderr
    text = (INCLUDE_DIR / "ni_flit_constants.h").read_text(encoding="ascii")
    assert "FLIT_WIDTH" in text
    assert "namespace ni" in text


def test_packet_cpp_has_provenance_banner():
    r = run_codegen("--target", "cpp", "--domain", "packet",
                    "--out", str(INCLUDE_DIR))
    assert r.returncode == 0, r.stderr
    text = (INCLUDE_DIR / "ni_flit_constants.h").read_text(encoding="ascii")
    assert "AUTO-GENERATED by tools/codegen.py" in text
    assert "Source SHA:" in text
    assert "Generator version:" in text
    assert "Generated at:" in text


def test_signals_cpp_emits_namespace():
    r = run_codegen("--target", "cpp", "--domain", "signals",
                    "--out", str(INCLUDE_DIR))
    assert r.returncode == 0, r.stderr
    text = (INCLUDE_DIR / "ni_signals.h").read_text(encoding="ascii")
    assert "namespace ni" in text
    assert "namespace signals" in text
    # Should have at least one reset constant for output signals
    assert "_RESET" in text


def test_signals_cpp_has_provenance_banner():
    text = (INCLUDE_DIR / "ni_signals.h").read_text(encoding="ascii")
    assert "Source SHA:" in text



# ---------------------------------------------------------------------------
# --check mode tests
# ---------------------------------------------------------------------------

def test_check_mode_exits_zero_when_clean():
    """--check must exit 0 when committed headers match fresh regen."""
    # First ensure headers are fresh
    for domain in ("packet", "signals", "params"):
        run_codegen("--target", "cpp", "--domain", domain, "--out", str(INCLUDE_DIR))
    r = run_codegen("--check")
    assert r.returncode == 0, (
        f"--check should exit 0 when headers are fresh.\n"
        f"stdout: {r.stdout}\nstderr: {r.stderr}"
    )


def test_check_mode_exits_one_on_drift(tmp_path):
    """--check must exit 1 when a committed header has been modified."""
    # First ensure headers are fresh
    for domain in ("packet", "signals", "params"):
        run_codegen("--target", "cpp", "--domain", domain, "--out", str(INCLUDE_DIR))

    target_header = INCLUDE_DIR / "ni_flit_constants.h"
    original_text = target_header.read_text(encoding="ascii")

    try:
        # Inject a fake drift line
        drifted = original_text + "\n// DRIFT INJECTED FOR TEST\n"
        target_header.write_text(drifted, encoding="ascii")

        r = run_codegen("--check")
        assert r.returncode == 1, (
            "--check should exit 1 when a header has drifted"
        )
    finally:
        # Restore the header regardless of test outcome
        target_header.write_text(original_text, encoding="ascii")


# ---------------------------------------------------------------------------
# Compilation regression test
# ---------------------------------------------------------------------------

def test_use_constants_cpp_compiles_and_runs(tmp_path):
    """examples/use_constants.cpp must compile and produce the expected output."""
    if not shutil.which("g++"):
        pytest.skip("g++ not in PATH")

    # Regenerate packet header
    run_codegen("--target", "cpp", "--domain", "packet", "--out", str(INCLUDE_DIR))

    exe = tmp_path / "use_constants_test.exe"
    src = SPECGEN_ROOT / "examples" / "use_constants.cpp"

    compile_result = subprocess.run(
        ["g++", "-std=c++17",
         "-I", str(INCLUDE_DIR),
         str(src),
         "-o", str(exe)],
        capture_output=True, text=True,
    )
    assert compile_result.returncode == 0, (
        f"Compilation failed:\n{compile_result.stderr}"
    )

    run_result = subprocess.run(
        [str(exe)], capture_output=True, text=True,
    )
    assert run_result.returncode == 0, run_result.stderr
    # All optional fields disabled: axi_ch is the first enabled field at LSB 0,
    # so packed hex of (axi_ch=2, src_id=5, dst_id=0x12, last=1, rob_req=1,
    # rob_idx=7) is the minimal-header value.
    assert "0x0000000007C0902A" in run_result.stdout, (
        f"Expected header value not found in output:\n{run_result.stdout}"
    )


# ---------------------------------------------------------------------------
# C++ static_assert presence tests (design doc sec 6.4)
# ---------------------------------------------------------------------------

def test_packet_cpp_has_flit_width_static_assert():
    """ni_flit_constants.h must contain FLIT_WIDTH static_assert."""
    text = (INCLUDE_DIR / "ni_flit_constants.h").read_text(encoding="ascii")
    assert "static_assert" in text
    assert "FLIT_WIDTH" in text
    assert "HEADER_WIDTH + PAYLOAD_WIDTH" in text


def test_packet_cpp_secded_static_assert_gated_on_flit_ecc():
    """SECDED bound static_assert is emitted only when flit_ecc is enabled.

    flit_ecc is currently disabled (width 0), so the codegen must NOT emit the
    SECDED assert (1 << 0 >= data_bits + ... would be false at compile time).
    """
    text = (INCLUDE_DIR / "ni_flit_constants.h").read_text(encoding="ascii")
    assert "SECDED bound" not in text



# ---------------------------------------------------------------------------
# per-field enabled flag tests (header_fields)
# ---------------------------------------------------------------------------

def test_packet_cpp_has_enabled_constants():
    """ni_flit_constants.h must contain _ENABLED bool constants for every header field."""
    r = run_codegen("--target", "cpp", "--domain", "packet",
                    "--out", str(INCLUDE_DIR))
    assert r.returncode == 0, r.stderr
    text = (INCLUDE_DIR / "ni_flit_constants.h").read_text(encoding="ascii")
    assert "constexpr bool" in text
    assert "_ENABLED" in text


def test_packet_cpp_padding_fields_have_enabled_false():
    """Fields declared as padding must emit ENABLED = false in C++ header.

    Post fixed-56b refactor: only the synthetic ``rsvd`` field is padding
    (derived width = HEADER_TOTAL_WIDTH - sum(enabled fields)).
    """
    text = (INCLUDE_DIR / "ni_flit_constants.h").read_text(encoding="ascii")
    assert "constexpr bool RSVD_ENABLED = false;" in text, (
        "Expected RSVD_ENABLED = false; not found in ni_flit_constants.h"
    )


def test_packet_cpp_functional_fields_have_enabled_true():
    """Functional fields must emit ENABLED = true in C++ header."""
    text = (INCLUDE_DIR / "ni_flit_constants.h").read_text(encoding="ascii")
    # axi_ch is MUST functional (AXI channel routing)
    for field in ("AXI_CH", "SRC_ID", "DST_ID", "VC_ID", "LAST", "ROB_REQ", "ROB_IDX"):
        assert f"constexpr bool {field}_ENABLED = true;" in text, (
            f"Expected {field}_ENABLED = true; not found in ni_flit_constants.h"
        )


# ---------------------------------------------------------------------------
# Pin-bundle compile smoke test
# ---------------------------------------------------------------------------

def test_padding_fields_array_elaborated():
    """ni_flit_constants.h must expose PaddingFieldPos struct + PADDING_FIELDS array."""
    from pathlib import Path
    text = (Path(__file__).resolve().parent.parent / "generated" / "cpp" / "ni_flit_constants.h").read_text()
    assert "struct PaddingFieldPos" in text, "missing PaddingFieldPos struct"
    assert "constexpr PaddingFieldPos PADDING_FIELDS[]" in text, "missing PADDING_FIELDS array"
    assert "constexpr std::size_t PADDING_FIELDS_COUNT" in text, "missing PADDING_FIELDS_COUNT"
    assert "rsvd" in text, \
        "expected synthetic 'rsvd' padding field in PADDING_FIELDS"


# ---------------------------------------------------------------------------
# Pin-bundle compile smoke test
# ---------------------------------------------------------------------------

def test_pins_bundle_compiles_with_gxx(tmp_path):
    """Smoke-compile ni::pins::*Pins bundle structs against elaborated header."""
    if not shutil.which("g++"):
        pytest.skip("g++ not in PATH")

    # Regenerate signals header so the test reflects the current spec.
    run_codegen("--target", "cpp", "--domain", "signals", "--out", str(INCLUDE_DIR))

    src = SPECGEN_ROOT / "tests" / "cpp_smoke" / "test_pins_compile.cpp"
    exe = tmp_path / "test_pins_compile.exe"
    r = subprocess.run(
        ["g++", "-std=c++17",
         "-I", str(INCLUDE_DIR),
         str(src),
         "-o", str(exe)],
        capture_output=True, text=True,
    )
    assert r.returncode == 0, f"g++ failed:\n{r.stderr}"
    # Also actually run the binary so reset_outputs() actually executes.
    run_result = subprocess.run([str(exe)], capture_output=True, text=True)
    assert run_result.returncode == 0, run_result.stderr


# ---------------------------------------------------------------------------
# Per-payload-field LSB/MSB constants (Task 3)
# ---------------------------------------------------------------------------

def test_packet_cpp_emits_payload_field_positions():
    """ni_flit_constants.h must contain per-channel payload field LSB/MSB constants."""
    text = (INCLUDE_DIR / "ni_flit_constants.h").read_text(encoding="ascii")
    # Per-channel namespace presence
    for ch_lower in ("aw", "ar", "w", "b", "r"):
        assert f"namespace payload::{ch_lower}" in text, (
            f"missing namespace payload::{ch_lower} block"
        )
    # Representative constant from each channel
    assert "constexpr int AWID_LSB" in text
    assert "constexpr int WDATA_LSB" in text
    assert "constexpr int BID_LSB" in text
    assert "constexpr int RDATA_LSB" in text


def test_packet_cpp_has_payload_static_assert():
    """Each payload channel must have a static_assert that field positions sum to channel width."""
    text = (INCLUDE_DIR / "ni_flit_constants.h").read_text(encoding="ascii")
    for ch in ("AW", "AR", "W", "B", "R"):
        assert f"ni::payload::{ch}_WIDTH" in text, f"missing static_assert for {ch}"


def test_emit_ni_params_h_matches_spec_derived_golden():
    """cpp_params.emit() output must match the hand-authored golden."""
    from tools.elaborate import cpp_params
    from ni_spec.loader import load_spec_version

    src = SPECGEN_ROOT / "source" / "constants.yaml"
    out = cpp_params.emit(src, load_spec_version())

    golden_path = Path(__file__).resolve().parent / "golden" / "ni_params.h.golden"
    golden = golden_path.read_text(encoding="ascii")
    assert out == golden, "emitted cpp output differs from spec-derived golden"
