"""Codegen smoke tests -- Task 7.

Tests cover:
- Each --target cpp --domain X produces a valid file with provenance banner.
- --check mode exits 0 when all committed headers match regen.
- --check mode detects drift when a header is modified.
- examples/use_constants.cpp still compiles and runs after regen.
- per-field enabled flag: ENABLED constants present in C++ header.
"""
from __future__ import annotations
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

SPECGEN_ROOT = Path(__file__).resolve().parent.parent
CODEGEN = SPECGEN_ROOT / "tools" / "codegen.py"
INCLUDE_DIR = SPECGEN_ROOT / "generated" / "cpp"


def run_codegen(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(CODEGEN), *args],
        capture_output=True,
        text=True,
        cwd=str(SPECGEN_ROOT),
    )


# ---------------------------------------------------------------------------
# Emit tests
# ---------------------------------------------------------------------------

def test_packet_cpp_emits_flit_width():
    r = run_codegen("--target", "cpp", "--domain", "packet",
                    "--out", str(INCLUDE_DIR))
    assert r.returncode == 0, r.stderr
    text = (INCLUDE_DIR / "ni_flit_constants.h").read_text(encoding="ascii")
    assert "FLIT_WIDTH" in text
    assert "namespace ni" in text


def test_packet_cpp_has_provenance_banner():
    r = run_codegen("--target", "cpp", "--domain", "packet",
                    "--out", str(INCLUDE_DIR))
    assert r.returncode == 0, r.stderr
    text = (INCLUDE_DIR / "ni_flit_constants.h").read_text(encoding="ascii")
    assert "AUTO-GENERATED by tools/codegen.py" in text
    assert "Source SHA:" in text
    assert "Generator version:" in text
    assert "Generated at:" in text


def test_signals_cpp_emits_namespace():
    r = run_codegen("--target", "cpp", "--domain", "signals",
                    "--out", str(INCLUDE_DIR))
    assert r.returncode == 0, r.stderr
    text = (INCLUDE_DIR / "ni_signals.h").read_text(encoding="ascii")
    assert "namespace ni" in text
    assert "namespace signals" in text
    # Should have at least one reset constant for output signals
    assert "_RESET" in text


def test_signals_cpp_has_provenance_banner():
    text = (INCLUDE_DIR / "ni_signals.h").read_text(encoding="ascii")
    assert "Source SHA:" in text


def test_registers_cpp_emits_offsets():
    r = run_codegen("--target", "cpp", "--domain", "registers",
                    "--out", str(INCLUDE_DIR))
    assert r.returncode == 0, r.stderr
    text = (INCLUDE_DIR / "ni_regs.h").read_text(encoding="ascii")
    assert "namespace regs" in text
    assert "_OFFSET" in text
    assert "enum class" in text  # access mode enums


def test_registers_cpp_has_provenance_banner():
    text = (INCLUDE_DIR / "ni_regs.h").read_text(encoding="ascii")
    assert "Source SHA:" in text


# ---------------------------------------------------------------------------
# --check mode tests
# ---------------------------------------------------------------------------

def test_check_mode_exits_zero_when_clean():
    """--check must exit 0 when committed headers match fresh regen."""
    # First ensure headers are fresh
    for domain in ("packet", "signals", "registers"):
        run_codegen("--target", "cpp", "--domain", domain, "--out", str(INCLUDE_DIR))
    r = run_codegen("--check")
    assert r.returncode == 0, (
        f"--check should exit 0 when headers are fresh.\n"
        f"stdout: {r.stdout}\nstderr: {r.stderr}"
    )


def test_check_mode_exits_one_on_drift(tmp_path):
    """--check must exit 1 when a committed header has been modified."""
    # First ensure headers are fresh
    for domain in ("packet", "signals", "registers"):
        run_codegen("--target", "cpp", "--domain", domain, "--out", str(INCLUDE_DIR))

    target_header = INCLUDE_DIR / "ni_flit_constants.h"
    original_text = target_header.read_text(encoding="ascii")

    try:
        # Inject a fake drift line
        drifted = original_text + "\n// DRIFT INJECTED FOR TEST\n"
        target_header.write_text(drifted, encoding="ascii")

        r = run_codegen("--check")
        assert r.returncode == 1, (
            "--check should exit 1 when a header has drifted"
        )
    finally:
        # Restore the header regardless of test outcome
        target_header.write_text(original_text, encoding="ascii")


# ---------------------------------------------------------------------------
# Compilation regression test
# ---------------------------------------------------------------------------

def test_use_constants_cpp_compiles_and_runs(tmp_path):
    """examples/use_constants.cpp must compile and produce the expected output."""
    if not shutil.which("g++"):
        pytest.skip("g++ not in PATH")

    # Regenerate packet header
    run_codegen("--target", "cpp", "--domain", "packet", "--out", str(INCLUDE_DIR))

    exe = tmp_path / "use_constants_test.exe"
    src = SPECGEN_ROOT / "examples" / "use_constants.cpp"

    compile_result = subprocess.run(
        ["g++", "-std=c++17",
         "-I", str(INCLUDE_DIR),
         str(src),
         "-o", str(exe)],
        capture_output=True, text=True,
    )
    assert compile_result.returncode == 0, (
        f"Compilation failed:\n{compile_result.stderr}"
    )

    run_result = subprocess.run(
        [str(exe)], capture_output=True, text=True,
    )
    assert run_result.returncode == 0, run_result.stderr
    assert "0x000000000F80902A" in run_result.stdout, (
        f"Expected header value not found in output:\n{run_result.stdout}"
    )


# ---------------------------------------------------------------------------
# C++ static_assert presence tests (design doc sec 6.4)
# ---------------------------------------------------------------------------

def test_packet_cpp_has_flit_width_static_assert():
    """ni_flit_constants.h must contain FLIT_WIDTH static_assert."""
    text = (INCLUDE_DIR / "ni_flit_constants.h").read_text(encoding="ascii")
    assert "static_assert" in text
    assert "FLIT_WIDTH" in text
    assert "HEADER_WIDTH + PAYLOAD_WIDTH" in text


def test_packet_cpp_has_secded_static_assert():
    """ni_flit_constants.h must contain SECDED bound static_assert."""
    text = (INCLUDE_DIR / "ni_flit_constants.h").read_text(encoding="ascii")
    assert "SECDED bound" in text


def test_registers_cpp_has_field_width_static_assert():
    """ni_regs.h must contain per-register field width sum static_assert."""
    text = (INCLUDE_DIR / "ni_regs.h").read_text(encoding="ascii")
    assert "static_assert" in text
    assert "field width sum" in text


# ---------------------------------------------------------------------------
# per-field enabled flag tests (header_fields)
# ---------------------------------------------------------------------------

def test_packet_cpp_has_enabled_constants():
    """ni_flit_constants.h must contain _ENABLED bool constants for every header field."""
    r = run_codegen("--target", "cpp", "--domain", "packet",
                    "--out", str(INCLUDE_DIR))
    assert r.returncode == 0, r.stderr
    text = (INCLUDE_DIR / "ni_flit_constants.h").read_text(encoding="ascii")
    assert "constexpr bool" in text
    assert "_ENABLED" in text


def test_packet_cpp_padding_fields_have_enabled_false():
    """Fields declared as padding must emit ENABLED = false in C++ header."""
    text = (INCLUDE_DIR / "ni_flit_constants.h").read_text(encoding="ascii")
    # These four are marked enabled=false per user direction (stubbed to zero, future-impl)
    for field in ("ROUTE_PAR", "RSVD_COMMTYPE", "MULTICAST", "FLIT_ECC"):
        assert f"constexpr bool {field}_ENABLED = false;" in text, (
            f"Expected {field}_ENABLED = false; not found in ni_flit_constants.h"
        )


def test_packet_cpp_functional_fields_have_enabled_true():
    """Functional fields must emit ENABLED = true in C++ header."""
    text = (INCLUDE_DIR / "ni_flit_constants.h").read_text(encoding="ascii")
    # axi_ch is MUST functional (AXI channel routing)
    for field in ("AXI_CH", "SRC_ID", "DST_ID", "VC_ID", "LAST", "ROB_REQ", "ROB_IDX"):
        assert f"constexpr bool {field}_ENABLED = true;" in text, (
            f"Expected {field}_ENABLED = true; not found in ni_flit_constants.h"
        )


# ---------------------------------------------------------------------------
# Pin-bundle compile smoke test
# ---------------------------------------------------------------------------

def test_padding_fields_array_elaborated():
    """ni_flit_constants.h must expose PaddingFieldPos struct + PADDING_FIELDS array."""
    from pathlib import Path
    text = (Path(__file__).resolve().parent.parent / "generated" / "cpp" / "ni_flit_constants.h").read_text()
    assert "struct PaddingFieldPos" in text, "missing PaddingFieldPos struct"
    assert "constexpr PaddingFieldPos PADDING_FIELDS[]" in text, "missing PADDING_FIELDS array"
    assert "constexpr std::size_t PADDING_FIELDS_COUNT" in text, "missing PADDING_FIELDS_COUNT"
    assert "route_par" in text or "flit_ecc" in text, \
        "expected at least one of route_par / flit_ecc in PADDING_FIELDS"


# ---------------------------------------------------------------------------
# Pin-bundle compile smoke test
# ---------------------------------------------------------------------------

def test_pins_bundle_compiles_with_gxx(tmp_path):
    """Smoke-compile ni::pins::*Pins bundle structs against elaborated header."""
    if not shutil.which("g++"):
        pytest.skip("g++ not in PATH")

    # Regenerate signals header so the test reflects the current spec.
    run_codegen("--target", "cpp", "--domain", "signals", "--out", str(INCLUDE_DIR))

    src = SPECGEN_ROOT / "tests" / "cpp_smoke" / "test_pins_compile.cpp"
    exe = tmp_path / "test_pins_compile.exe"
    r = subprocess.run(
        ["g++", "-std=c++17",
         "-I", str(INCLUDE_DIR),
         str(src),
         "-o", str(exe)],
        capture_output=True, text=True,
    )
    assert r.returncode == 0, f"g++ failed:\n{r.stderr}"
    # Also actually run the binary so reset_outputs() actually executes.
    run_result = subprocess.run([str(exe)], capture_output=True, text=True)
    assert run_result.returncode == 0, run_result.stderr
