"""Codegen SV emitter tests -- Task 8.

Tests cover:
- --target sv --domain {packet|signals|params} each produces a .sv file.
- Each .sv file has the correct package / endpackage structure.
- localparam int unsigned present in files.
- Provenance banner (AUTO-GENERATED, Source SHA, Generator version, Generated at).
- ifndef/define/endif include guard in files.
- --check mode covers SV files (detects drift, passes when clean).
- --lint-sv skips gracefully when verilator is not in PATH.
"""
from __future__ import annotations
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

SPECGEN_ROOT = Path(__file__).resolve().parent.parent
CODEGEN = SPECGEN_ROOT / "tools" / "codegen.py"
RTL_PKG_DIR = SPECGEN_ROOT / "generated" / "sv"


def run_codegen(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(CODEGEN), *args],
        capture_output=True,
        text=True,
        cwd=str(SPECGEN_ROOT),
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _sv_text(filename: str) -> str:
    """Read committed SV file (regenerate first to ensure it exists)."""
    path = RTL_PKG_DIR / filename
    if not path.exists():
        pytest.skip(f"{filename} not found; run --target sv first")
    return path.read_text(encoding="ascii")


# ---------------------------------------------------------------------------
# Emit tests -- one per domain
# ---------------------------------------------------------------------------

class TestSvPacketEmit:
    def setup_method(self):
        r = run_codegen("--target", "sv", "--domain", "packet",
                        "--out", str(RTL_PKG_DIR))
        assert r.returncode == 0, r.stderr

    def test_exits_zero(self):
        r = run_codegen("--target", "sv", "--domain", "packet",
                        "--out", str(RTL_PKG_DIR))
        assert r.returncode == 0, r.stderr

    def test_file_exists(self):
        assert (RTL_PKG_DIR / "ni_flit_pkg.sv").exists()

    def test_package_structure(self):
        text = _sv_text("ni_flit_pkg.sv")
        assert "package ni_flit_pkg;" in text
        assert "endpackage" in text

    def test_localparam_int_unsigned(self):
        text = _sv_text("ni_flit_pkg.sv")
        assert "localparam int unsigned" in text

    def test_flit_width_constant(self):
        text = _sv_text("ni_flit_pkg.sv")
        assert "FLIT_WIDTH" in text

    def test_header_field_lsb_msb(self):
        text = _sv_text("ni_flit_pkg.sv")
        assert "ROB_IDX_LSB" in text
        assert "ROB_IDX_MSB" in text

    def test_ifndef_include_guard(self):
        text = _sv_text("ni_flit_pkg.sv")
        assert "`ifndef NI_FLIT_PKG_SVH" in text
        assert "`define NI_FLIT_PKG_SVH" in text
        assert "`endif" in text

    def test_provenance_banner(self):
        text = _sv_text("ni_flit_pkg.sv")
        assert "AUTO-GENERATED by tools/codegen.py" in text
        assert "Source SHA:" in text
        assert "Generator version:" in text
        assert "Generated at:" in text

    def test_enabled_localparams_present(self):
        """ni_flit_pkg.sv must contain localparam bit _ENABLED constants."""
        text = _sv_text("ni_flit_pkg.sv")
        assert "localparam bit" in text
        assert "_ENABLED" in text

    def test_padding_fields_enabled_zero(self):
        """Fields declared as padding must emit ENABLED = 1'b0 in SV package.

        Post fixed-56b refactor: only the synthetic ``rsvd`` field is padding.
        """
        text = _sv_text("ni_flit_pkg.sv")
        assert "localparam bit          RSVD_ENABLED = 1'b0;" in text, (
            "Expected RSVD_ENABLED = 1'b0; not found in ni_flit_pkg.sv"
        )

    def test_functional_fields_enabled_one(self):
        """Functional fields must emit ENABLED = 1'b1 in SV package."""
        text = _sv_text("ni_flit_pkg.sv")
        # axi_ch is MUST functional (AXI channel routing)
        for field in ("AXI_CH", "SRC_ID", "DST_ID", "VC_ID", "LAST", "ROB_REQ", "ROB_IDX"):
            assert f"localparam bit          {field}_ENABLED = 1'b1;" in text, (
                f"Expected {field}_ENABLED = 1'b1; not found in ni_flit_pkg.sv"
            )

    def test_payload_field_positions_emitted(self):
        """ni_flit_pkg.sv must contain per-channel-prefixed payload field constants."""
        text = _sv_text("ni_flit_pkg.sv")
        # Representative constants from each channel
        for sig in ("AW_AWID_LSB", "AR_ARID_LSB", "W_WDATA_LSB",
                    "B_BID_LSB", "R_RDATA_LSB"):
            assert f"localparam int unsigned {sig}" in text, (
                f"missing {sig} in ni_flit_pkg.sv"
            )


class TestSvSignalsEmit:
    def setup_method(self):
        r = run_codegen("--target", "sv", "--domain", "signals",
                        "--out", str(RTL_PKG_DIR))
        assert r.returncode == 0, r.stderr

    def test_exits_zero(self):
        r = run_codegen("--target", "sv", "--domain", "signals",
                        "--out", str(RTL_PKG_DIR))
        assert r.returncode == 0, r.stderr

    def test_file_exists(self):
        assert (RTL_PKG_DIR / "ni_signals_pkg.sv").exists()

    def test_package_structure(self):
        text = _sv_text("ni_signals_pkg.sv")
        assert "package ni_signals_pkg;" in text
        assert "endpackage" in text

    def test_localparam_int_unsigned(self):
        text = _sv_text("ni_signals_pkg.sv")
        # Either contains a constant OR explains there are no reset values.
        assert "localparam int unsigned" in text or "No output signals" in text

    def test_ifndef_include_guard(self):
        text = _sv_text("ni_signals_pkg.sv")
        assert "`ifndef NI_SIGNALS_PKG_SVH" in text
        assert "`define NI_SIGNALS_PKG_SVH" in text
        assert "`endif" in text

    def test_provenance_banner(self):
        text = _sv_text("ni_signals_pkg.sv")
        assert "Source SHA:" in text

    def test_emits_noc_struct_typedefs(self):
        run_codegen("--target", "sv", "--domain", "signals", "--out", str(RTL_PKG_DIR))
        sv = (RTL_PKG_DIR / "ni_signals_pkg.sv").read_text(encoding="ascii")
        assert "} noc_chan_t;" in sv
        assert "} axi_req_t;" in sv and "} axi_rsp_t;" in sv

    def test_struct_typedefs_in_package(self):
        sv = (RTL_PKG_DIR / "ni_signals_pkg.sv").read_text(encoding="ascii")
        pkg = sv[sv.index("package ni_signals_pkg"):sv.index("endpackage")]
        assert "noc_chan_t" in pkg and "axi_req_t" in pkg     # typedef 在 package 內

    def test_ni_signals_fixed_typedefs_no_credit(self):
        run_codegen("--target", "sv", "--domain", "signals", "--out", str(RTL_PKG_DIR))
        sv = (RTL_PKG_DIR / "ni_signals_pkg.sv").read_text(encoding="ascii")
        assert "} noc_chan_t;" in sv and "} axi_req_t;" in sv and "} axi_rsp_t;" in sv
        assert "noc_credit_t" not in sv          # 已移到 noc_types_pkg

    def test_noc_types_pkg_per_vc(self, tmp_path):
        for num_vc, expected_width in ((1, "[0:0]"), (2, "[1:0]"), (4, "[3:0]"), (8, "[7:0]")):
            run_codegen("--target", "sv", "--domain", "noc_types",
                        "--num-vc", str(num_vc), "--out", str(tmp_path))
            sv = (tmp_path / f"noc_types_pkg_vc{num_vc}.sv").read_text(encoding="ascii")
            assert "package noc_types_pkg" in sv, f"vc{num_vc}: missing package declaration"
            assert "} noc_credit_t;" in sv, f"vc{num_vc}: missing noc_credit_t typedef"
            assert expected_width in sv, f"vc{num_vc}: expected credit width {expected_width}"

    def test_noc_types_pkg_invalid_vc_rejected(self):
        """--num-vc with an invalid value must exit non-zero with an error message."""
        for invalid in (0, 3, 5, 16):
            r = run_codegen("--target", "sv", "--domain", "noc_types",
                            "--num-vc", str(invalid))
            assert r.returncode != 0, f"--num-vc {invalid} should be rejected"
            assert "invalid" in r.stderr.lower() or "must be one of" in r.stderr.lower(), (
                f"--num-vc {invalid}: expected error message, got: {r.stderr}"
            )


# ---------------------------------------------------------------------------
# --check mode covers SV files
# ---------------------------------------------------------------------------

class TestCheckModeWithSv:
    def setup_method(self):
        """Ensure all SV files are freshly generated before each check test."""
        for domain in ("packet", "signals", "params"):
            run_codegen("--target", "sv", "--domain", domain, "--out", str(RTL_PKG_DIR))
        # Also ensure C++ headers are fresh.
        from tests.test_codegen import INCLUDE_DIR
        for domain in ("packet", "signals", "params"):
            run_codegen("--target", "cpp", "--domain", domain, "--out", str(INCLUDE_DIR))

    def test_check_exits_zero_when_sv_clean(self):
        """--check must exit 0 when all SV files match fresh regen."""
        r = run_codegen("--check")
        assert r.returncode == 0, (
            f"--check should exit 0 when SV files are fresh.\n"
            f"stdout: {r.stdout}\nstderr: {r.stderr}"
        )

    def test_check_exits_one_on_sv_drift(self):
        """--check must exit 1 when a committed SV file has drifted."""
        target_sv = RTL_PKG_DIR / "ni_flit_pkg.sv"
        original_text = target_sv.read_text(encoding="ascii")
        try:
            drifted = original_text + "\n// DRIFT INJECTED FOR TEST\n"
            target_sv.write_text(drifted, encoding="ascii")
            r = run_codegen("--check")
            assert r.returncode == 1, "--check should exit 1 when SV has drifted"
        finally:
            target_sv.write_text(original_text, encoding="ascii")


# ---------------------------------------------------------------------------
# --lint-sv graceful skip
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Task 4: Pin-level SV interface per bundle
# ---------------------------------------------------------------------------

def test_interfaces_removed():
    """ni_signals_pkg.sv must NOT emit any SV interface after the FlooNoC struct
    refactor — every wrap/fabric/tb port now uses the packed-struct typedefs
    (noc_chan_t / axi_req_t / axi_rsp_t). The interface_handshake.json source
    still drives the struct field/channel order, but no interface is emitted.
    """
    # Ensure the SV file is freshly regenerated before reading.
    r = run_codegen("--target", "sv", "--domain", "signals", "--out", str(RTL_PKG_DIR))
    assert r.returncode == 0, r.stderr

    sv = (RTL_PKG_DIR / "ni_signals_pkg.sv").read_text(encoding="ascii")
    assert "interface noc_intf" not in sv and "interface axi4_intf" not in sv
    # No stray interface/modport/endinterface tokens at all.
    assert "interface " not in sv and "modport " not in sv and "endinterface" not in sv


class TestLintSv:
    def test_lint_sv_graceful_skip_or_pass(self):
        """--lint-sv must exit 0 (either skip or lint pass; never crash)."""
        # First ensure SV files exist.
        for domain in ("packet", "signals", "params"):
            run_codegen("--target", "sv", "--domain", domain, "--out", str(RTL_PKG_DIR))

        r = run_codegen("--lint-sv")
        # Either 0 (skip or pass) or non-zero only if verilator found a real lint error.
        # Since we can't guarantee verilator outcome on all CI envs, we just confirm
        # it doesn't crash with an exception (non-zero return from subprocess == lint warning).
        # The requirement is that absence of verilator exits 0, not that lint is perfect.
        if shutil.which("verilator") is None:
            assert r.returncode == 0, (
                f"--lint-sv must exit 0 when verilator not in PATH.\n"
                f"stderr: {r.stderr}"
            )
            assert "skip" in r.stderr.lower(), (
                f"Expected [skip] message in stderr when verilator absent.\n"
                f"stderr: {r.stderr}"
            )
        # If verilator IS present, returncode may be 0 or non-zero depending on
        # lint warnings -- we just verify the command ran without Python exceptions.
        assert "Traceback" not in r.stderr, (
            f"--lint-sv raised a Python exception:\n{r.stderr}"
        )

    def test_lint_sv_no_python_exception_without_verilator(self, monkeypatch):
        """Simulate verilator missing by overriding PATH, confirm graceful skip."""
        import os
        env = os.environ.copy()
        env["PATH"] = ""  # empty PATH -> shutil.which("verilator") returns None
        result = subprocess.run(
            [sys.executable, str(CODEGEN), "--lint-sv"],
            capture_output=True,
            text=True,
            env=env,
            cwd=str(SPECGEN_ROOT),
        )
        assert result.returncode == 0, f"Expected exit 0, got {result.returncode}.\nstderr: {result.stderr}"
        assert "skip" in result.stderr.lower(), (
            f"Expected skip message.\nstderr: {result.stderr}"
        )



def test_emit_ni_params_pkg_sv_matches_spec_derived_golden():
    """sv_params.emit() output must match the hand-authored golden from spec §5.2."""
    from tools.elaborate import sv_params
    from ni_spec.loader import load_spec_version

    src = SPECGEN_ROOT / "source" / "constants.yaml"
    out = sv_params.emit(src, load_spec_version())

    golden_path = Path(__file__).resolve().parent / "golden" / "ni_params_pkg.sv.golden"
    golden = golden_path.read_text(encoding="ascii")
    assert out == golden, "emitted output differs from spec-derived golden"
