"""Shared codegen helpers -- provenance banner (design doc §6.6)."""
from __future__ import annotations
from datetime import datetime, timezone
import hashlib
from pathlib import Path

# Repo root is two levels above this file: tools/elaborate/common.py -> spec_validate/ -> noc-sim/
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent


def _repo_relative(path: Path) -> str:
    """Return path relative to the repo root as a POSIX string, or abs path if outside."""
    try:
        return path.resolve().relative_to(_REPO_ROOT).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def provenance_banner(
    source_json_path: Path,
    *,
    generator_version: str = "v1.0.0",
    comment_prefix: str = "//",
) -> str:
    """Return the provenance banner required by design doc §6.6.

    The '// Generated at:' line is last so --check mode can strip it by
    matching that prefix without disturbing the other stable lines.
    """
    json_bytes = source_json_path.read_bytes()
    sha = hashlib.sha256(json_bytes).hexdigest()[:12]
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    rel_path = _repo_relative(source_json_path)
    sep = f"{comment_prefix} " + "-" * 76
    lines = [
        sep,
        f"{comment_prefix} AUTO-GENERATED by tools/codegen.py -- DO NOT EDIT",
        f"{comment_prefix} Source:    {rel_path}",
        f"{comment_prefix} Source SHA: {sha}",
        f"{comment_prefix} Generator version: {generator_version}",
        f"{comment_prefix} Generated at: {ts}",
        sep,
        "",
    ]
    return "\n".join(lines)
