#!/usr/bin/env python
"""Generate c_model/FEATURE_INVENTORY.md from ni_function_blocks.json.

Standalone (not part of tools/codegen.py): inventory is documentation, not
C++/SV code. Run after editing ni_function_blocks.json to keep the MD in sync.

Drift gate: tests/test_feature_inventory.py regenerates to a tempfile and
diffs against the committed MD (timestamp banner line excluded).
"""
from __future__ import annotations
import argparse
import datetime
import json
import sys
from pathlib import Path

SPECGEN_ROOT = Path(__file__).resolve().parent.parent
JSON_PATH    = SPECGEN_ROOT / "source" / "ni_function_blocks.json"
DEFAULT_OUT  = SPECGEN_ROOT.parent / "c_model" / "FEATURE_INVENTORY.md"


def _expected_header(feat_id: str) -> str:
    """FEAT-NMU-AXI_SLAVE_PORT -> c_model/include/nmu/axi_slave_port.hpp"""
    parts = feat_id.split("-")
    if len(parts) < 3 or parts[0] != "FEAT":
        return "(unknown id format)"
    block = parts[1].lower()
    short = "_".join(parts[2:]).lower()
    return f"c_model/include/{block}/{short}.hpp"


def _format_modes(modes):
    if not modes:
        return "—"
    return ", ".join(modes)


def render(spec, when):
    out = []
    out.append(f"<!-- AUTO-GENERATED by spec_validate/tools/gen_inventory.py — DO NOT EDIT -->")
    out.append(f"<!-- Source: spec_validate/authored/ni_function_blocks.json -->")
    out.append(f"<!-- Generated at: {when} -->")
    out.append("")
    out.append("# NI Feature Inventory")
    out.append("")
    out.append("Inventory of NMU / NSU features defined in `ni_function_blocks.json`. ")
    out.append("Per Invariant 1, the JSON does not drive codegen of internal unit classes; ")
    out.append("this file is documentation + a drift gate.")
    out.append("")
    out.append("Column **Expected c_model header** points to the conventional path for that ")
    out.append("feature's c_model implementation. Existence is **not enforced** — most features ")
    out.append("won't have an implementation until Layer B / Stage 2.")
    out.append("")
    for block in spec.get("blocks", []):
        name = block["name"]
        full = block.get("fullname", "")
        role = block.get("role", "")
        out.append(f"## {name} — {full}")
        out.append("")
        if role:
            out.append(f"_Role_: {role}")
            out.append("")
        out.append("| Feature ID | Summary | Modes | Expected c_model header |")
        out.append("|---|---|---|---|")
        for feat in block.get("features", []):
            fid     = feat["id"]
            summary = feat.get("summary", "").replace("|", "\\|")
            modes   = _format_modes(feat.get("modes"))
            hdr     = _expected_header(fid)
            out.append(f"| `{fid}` | {summary} | {modes} | `{hdr}` |")
        out.append("")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description="Generate c_model/FEATURE_INVENTORY.md")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--check", action="store_true",
                    help="Verify committed MD matches regen (timestamp excluded). Exit 1 on drift.")
    args = ap.parse_args()
    spec = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    when = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    body = render(spec, when)
    if args.check:
        if not args.out.exists():
            print(f"FAIL: committed inventory missing at {args.out}", file=sys.stderr)
            sys.exit(1)
        existing = args.out.read_text(encoding="utf-8")
        strip = lambda t: "\n".join(
            l for l in t.splitlines() if not l.startswith("<!-- Generated at:"))
        if strip(body) != strip(existing):
            print(f"FAIL: inventory drift at {args.out}", file=sys.stderr)
            sys.exit(1)
        sys.exit(0)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(body, encoding="utf-8")
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
