#!/usr/bin/env python3
"""Generate sim/sv/tb_top.sv from a topology config + specgen constants.

S0 scope: reproduce 2-node single-VC tb behaviour.  Generated artifact: edit
the generator or the topology YAML, never the emitted .sv directly.

Usage:
    python3 gen_tb_top.py [--topology mesh_2x1] [--out sim/sv/tb_top.sv]
    python3 gen_tb_top.py --check            # drift gate (exit 1 if stale)

Parameterised from topology YAML:
    - nodes list [(x,y), ...] from x_dim × y_dim
    - per-node plusarg names (+scenario_node<i>)
    - per-node variable declarations (ctx handles, scenario strings)
    - cmodel_init called with the LAST node's scenario (matches original hand-written order)
    - master at node k drives the NEXT node's variant (circular, crosses link)
    - slave  at node k receives the NEXT node's variant
    - src_id = linear index = x + y*x_dim (same as node index for 1D mesh)
    - inter-router link nets named <type>_<src>to<dst> for each neighbour pair
    - PASS guard: cmodel_master_count() == len(nodes)

Constants kept as template (not derived from topology YAML):
    - clk/rst timing (10 ns clock, 4-cycle reset)
    - TIMEOUT_CYCLES = 100000
    - localparam width constants from ni_params_pkg
    - DPI function signatures
    - perf instrumentation, FSDB block, DPI error poll structure
"""

import argparse
import difflib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def load_topology(name: str) -> dict:
    import yaml
    path = ROOT / "sim" / "topologies" / f"{name}.yaml"
    return yaml.safe_load(path.read_text())


# ---------------------------------------------------------------------------
# Emit helpers
# ---------------------------------------------------------------------------

def _node_id(x: int, y: int, x_dim: int) -> int:
    """Linear node index, same as src_id."""
    return x + y * x_dim


def _node_label(i: int) -> str:
    return str(i)


def _scenario_var(i: int) -> str:
    return f"scn_node{i}"


def _ctx_vars(i: int) -> tuple:
    """Return (router_ctx, m_ctx, s_ctx, nmu_ctx, nsu_ctx) variable names."""
    return (
        f"router{i}_ctx",
        f"m{i}_ctx",
        f"s{i}_ctx",
        f"n{i}_nmu_ctx",
        f"n{i}_nsu_ctx",
    )


def emit_tb_top(topo: dict) -> str:
    x_dim = topo["topology"]["x_dim"]
    y_dim = topo["topology"]["y_dim"]
    nodes = [(x, y) for y in range(y_dim) for x in range(x_dim)]
    n = len(nodes)
    ids = [_node_id(x, y, x_dim) for x, y in nodes]  # src_id per node

    # S0 scope guard: only the 2-node line is supported. router_wrap exposes a
    # single inter-router link port pair; topologies where any node needs more
    # than one inter-router link require directional N/E/S/W ports (Task 7).
    if (x_dim, y_dim) != (2, 1):
        sys.exit("gen_tb_top: topology needs directional N/E/S/W ports — "
                 "not supported until Task 7; S0 supports the 2-node line only")

    # ------------------------------------------------------------------
    # Explicit per-node mapping (no modular arithmetic at emit time).
    # Each node i owns:
    #   - a master fed the NEXT node's scenario (traffic crosses the link)
    #   - a SLAVE that ejects the traffic the master sent — that slave lives at
    #     the destination node (next_i), is named slave_{next_i}, wired to bus
    #     nsu_slave_axi_{next_i}, and its ctx handle is created in node i's
    #     initial block (s{i}_ctx).
    # slave_map[j] records, for the slave instance at node j, the (ctx_var, bus,
    # scenario) triple so the instance section states name→ctx→bus together
    # rather than re-deriving the alias.
    masters = []   # list of dicts, one per node, in node order
    slave_map = {}  # slave node index -> dict(ctx_var, bus, scenario, owner)
    for i in ids:
        next_i = (i + 1) % n
        _, m_ctx, s_ctx, nmu_ctx, nsu_ctx = _ctx_vars(i)
        masters.append({
            "node": i,
            "m_ctx": m_ctx,
            "nmu_ctx": nmu_ctx,
            "nsu_ctx": nsu_ctx,
            "scenario": _scenario_var(next_i),
            "dest": next_i,
        })
        # The slave that receives node i's master traffic is at node next_i.
        slave_map[next_i] = {
            "ctx_var": s_ctx,                       # created in node i's block
            "bus": f"nsu_slave_axi_{next_i}",       # AXI bus at the dest node
            "scenario": _scenario_var(next_i),      # dest-range scenario
            "owner": i,                             # initial-block that creates it
        }

    lines = []
    w = lines.append

    # ------------------------------------------------------------------
    # File header
    # ------------------------------------------------------------------
    w("`timescale 1ns/1ps")
    w("")
    w("// AUTO-GENERATED by sim/tools/gen_tb_top.py")
    w(f"// Topology: {topo['topology']['name']}  "
      f"({x_dim}x{y_dim}, num_vc={topo['topology']['num_vc']})")
    w("// DO NOT EDIT — modify the generator or sim/topologies/*.yaml instead.")
    w("//")
    w("// Behaviour description:")
    w(f"// {n} symmetric nodes, each driving its own per-node router_wrap, joined by")
    w("// cross-node link(s).")
    w("//   node k:  axi_master_wrap →[master_nmu_axi_k]→ nmu_wrap →[nodeK_nmu]→")
    w("//            router_wrap[k] ←link→ router_wrap[k+1] (circular)")
    w("//            router_wrap[k] →[nodeK_nsu]→ nsu_wrap →[nsu_slave_axi_k]→ axi_slave_wrap")
    w("// Variant→instance pairing: master at node k is fed the NEXT node's scenario")
    w("// so traffic crosses the link. src_id matches each node's linear index.")
    w("//")
    w("// Self-clocked: clk_i/rst_ni are internal logic (10 ns clock, 4-cycle reset).")
    w("// Plusargs +scenario_node0=<path> ... +scenario_node{N-1}=<path> kick off the run;")
    w("// cmodel_init is called once with the last node's variant (shared config).")
    w("")
    w("`ifndef TB_TOP_SV")
    w("`define TB_TOP_SV")
    w("")
    w("module tb_top;")
    w("    logic clk_i  = 1'b0;")
    w("    logic rst_ni = 1'b0;")
    w("    always #5 clk_i = ~clk_i;")
    w("    initial begin")
    w("        repeat (4) @(posedge clk_i);")
    w("        rst_ni = 1'b1;")
    w("    end")
    w("    localparam int unsigned TIMEOUT_CYCLES = 100000;")
    w("    initial begin")
    w("        repeat (TIMEOUT_CYCLES) @(posedge clk_i);")
    w('        $fatal(1, "tb_top: timeout after %0d cycles", TIMEOUT_CYCLES);')
    w("    end")
    w("")
    w("    // -------------------------------------------------------------------------")
    w("    // Parameters")
    w("    // -------------------------------------------------------------------------")
    w("    localparam int unsigned ID_WIDTH              = ni_params_pkg::AXI_ID_WIDTH_DFLT;")
    w("    localparam int unsigned ADDR_WIDTH            = ni_params_pkg::AXI_ADDR_WIDTH_DFLT;")
    w("    localparam int unsigned DATA_WIDTH            = ni_params_pkg::AXI_DATA_WIDTH_DFLT;")
    num_vc = topo["topology"]["num_vc"]
    w(f"    localparam int unsigned NUM_VC                = {num_vc};  // from topology YAML (single source)")
    w("    localparam int unsigned FLIT_WIDTH            = ni_params_pkg::NOC_FLIT_WIDTH_DFLT;")
    w("    localparam int unsigned SLAVE_VC_BUFFER_DEPTH = ni_params_pkg::NOC_SLAVE_VC_BUFFER_DEPTH_DFLT;")
    w("")
    w("    // -------------------------------------------------------------------------")
    w("    // DPI lifecycle")
    w("    // -------------------------------------------------------------------------")
    w('    import "DPI-C" context function void    cmodel_init(input string path);')
    w('    import "DPI-C" context function void    cmodel_finalize();')
    w('    import "DPI-C" context function int     cmodel_done();')
    w('    import "DPI-C" context function int     cmodel_scoreboard_clean();')
    w('    import "DPI-C" context function void    cmodel_dump_scoreboard();')
    w('    import "DPI-C" context function longint unsigned cmodel_router_create(input string name, input int x_coord);')
    w('    import "DPI-C" context function longint unsigned cmodel_master_create(input string name,')
    w('                                                                 input string scenario_path);')
    w('    import "DPI-C" context function longint unsigned cmodel_slave_create(input string name,')
    w('                                                                input string scenario_path);')
    w('    import "DPI-C" context function longint unsigned cmodel_nmu_create(input string name, input int src_id);')
    w('    import "DPI-C" context function longint unsigned cmodel_nsu_create(input string name, input int src_id);')
    w('    import "DPI-C" context function int     cmodel_master_count();')
    w('    import "DPI-C" context function int     cmodel_reads_checked();')
    w("")

    # ------------------------------------------------------------------
    # Per-node variable declarations
    # ------------------------------------------------------------------
    # Scenario strings
    for i in ids:
        comment = ""
        if i == 0:
            comment = "  // node0 coordinate variant (low addr);  drives node1.master"
        elif i == n - 1:
            comment = f"  // node{n-1} coordinate variant (high addr); drives node0.master"
        w(f"    string  {_scenario_var(i)};{comment}")

    # Context handles
    for i in ids:
        r_ctx, m_ctx, s_ctx, nmu_ctx, nsu_ctx = _ctx_vars(i)
        w(f"    longint unsigned {r_ctx}, {m_ctx}, {s_ctx}, {nmu_ctx}, {nsu_ctx};")
    w("")

    # ------------------------------------------------------------------
    # Plusargs + cmodel_init + per-node create
    # ------------------------------------------------------------------
    w("    initial begin")

    # Plusarg check — all nodes must provide a scenario
    cond_parts = []
    for i in ids:
        cond_parts.append(f'!$value$plusargs("scenario_node{i}=%s", {_scenario_var(i)})')
    # Format as a multi-line if
    indent = "        "
    if len(cond_parts) == 1:
        w(f"{indent}if ({cond_parts[0]}) begin")
    else:
        w(f"{indent}if ({cond_parts[0]} ||")
        for part in cond_parts[1:-1]:
            w(f"{indent}    {part} ||")
        w(f"{indent}    {cond_parts[-1]}) begin")

    scn_args = " ".join(f"+scenario_node{i}=<path>" for i in ids)
    w(f'            $display("ERROR: {scn_args} required");')
    w("            $finish(1);")
    w("        end")

    # cmodel_init: use the last node's scenario (matches original convention)
    last_i = ids[-1]
    w(f"        cmodel_init({_scenario_var(last_i)});  // shared config; either variant is fine")

    # Router creates
    for i in ids:
        x = nodes[i][0]  # x_coord for the router
        r_ctx = _ctx_vars(i)[0]
        w(f'        {r_ctx} = cmodel_router_create("router_{i}", {x});')

    # Per-node creates, emitted from the explicit `masters` map. Each node i:
    #   - master fed the dest node's scenario (traffic crosses the link)
    #   - slave_{dest} created here (its ctx lives in node i's block); the slave
    #     INSTANCE is emitted later from slave_map, stating name→ctx→bus together.
    for m in masters:
        i = m["node"]
        dest = m["dest"]
        s = slave_map[dest]
        w(f"        // node{i}.master drives node{dest}-variant (targets node{dest}); ejects at node{dest}.NSU.")
        w(f'        {m["m_ctx"]}     = cmodel_master_create("master_{i}", {m["scenario"]});')
        w(f'        {s["ctx_var"]}     = cmodel_slave_create ("slave_{dest}",  {s["scenario"]});  '
          f'// node{dest}.slave: receives node{dest}-range data')
        w(f'        {m["nmu_ctx"]} = cmodel_nmu_create("nmu_{i}", {i});                '
          f'// src_id = node{i} coordinate')
        w(f'        {m["nsu_ctx"]} = cmodel_nsu_create("nsu_{i}", {i});')

    w("    end")
    w("")

    # ------------------------------------------------------------------
    # Wire bundles
    # ------------------------------------------------------------------
    w("    // -------------------------------------------------------------------------")
    w("    // Wire bundles — per-node × {master_nmu AXI, NMU-side NoC, NSU-side NoC, nsu_slave AXI}")
    w("    // -------------------------------------------------------------------------")
    axi_params = "        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)"
    noc_params = ("        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), "
                  ".SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)")

    for i in ids:
        w(f"")
        w(f"    // node{i}")
        w(f"    axi4_intf #(")
        w(f"{axi_params}")
        w(f"    ) master_nmu_axi_{i} ();")
        w(f"    noc_intf #(")
        w(f"{noc_params}")
        w(f"    ) node{i}_nmu ();")
        w(f"    noc_intf #(")
        w(f"{noc_params}")
        w(f"    ) node{i}_nsu ();")
        w(f"    axi4_intf #(")
        w(f"{axi_params}")
        w(f"    ) nsu_slave_axi_{i} ();")

    w("")

    # ------------------------------------------------------------------
    # Component instances — per node
    # ------------------------------------------------------------------
    for i in ids:
        _, m_ctx, s_ctx, nmu_ctx, nsu_ctx = _ctx_vars(i)
        next_i = (i + 1) % n
        w("    // -------------------------------------------------------------------------")
        w(f"    // Component instances — node{i}")
        w("    // -------------------------------------------------------------------------")
        w(f"    axi_master_wrap #(")
        w(f"        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)")
        w(f"    ) u_master_{i} (")
        w(f"        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i({m_ctx}), .axi_o(master_nmu_axi_{i}.master)")
        w(f"    );")
        w(f"")
        w(f"    nmu_wrap #(")
        w(f"        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH),")
        w(f"        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)")
        w(f"    ) u_nmu_{i} (")
        w(f"        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i({nmu_ctx}),")
        w(f"        .axi_i(master_nmu_axi_{i}.slave), .noc_mosi_o(node{i}_nmu.mosi)")
        w(f"    );")
        w(f"")
        w(f"    nsu_wrap #(")
        w(f"        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH),")
        w(f"        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)")
        w(f"    ) u_nsu_{i} (")
        w(f"        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i({nsu_ctx}),")
        w(f"        .noc_miso_i(node{i}_nsu.miso), .axi_o(nsu_slave_axi_{i}.master)")
        w(f"    );")
        w(f"")
        # Slave instance lives at node next_i (the destination of node i's master
        # traffic). Its name, ctx, and AXI bus come from slave_map[next_i] — stated
        # together, no modular re-derivation.
        slv = slave_map[next_i]
        w(f"    axi_slave_wrap #(")
        w(f"        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)")
        w(f"    ) u_slave_{next_i} (")
        w(f'        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i({slv["ctx_var"]}), '
          f'.axi_i({slv["bus"]}.slave)')
        w(f"    );")
        w(f"")

    # ------------------------------------------------------------------
    # Router fabric — inter-node links
    # ------------------------------------------------------------------
    w("    // -------------------------------------------------------------------------")
    w("    // Router fabric — per-node router_wraps joined by cross-wired links")
    w("    // -------------------------------------------------------------------------")
    w("    // Link nets named <net>_<src>to<dst>_*: data flows src->dst, credit pulse")
    w("    // flows on the net whose direction matches the credit's travel.")

    # For a 2-node mesh there is exactly one pair (0,1) with bidirectional links.
    # For general n-node ring, pairs are (i, (i+1)%n).
    # But for the 2-node mesh, node0→node1 and node1→node0 are distinct directed nets.
    # We emit link nets for each directed pair (i, next_i) where next_i > i only
    # (for a 2-node mesh that's just (0,1)); for a ring we'd do all n pairs.
    # S0 scope: 2-node mesh only has one bidirectional link between node0 and node1.

    # Collect unique undirected edges (for a 1D mesh: 0-1, 1-2, etc.)
    # For x_dim=2, y_dim=1: only edge (0,1)
    edges = []
    for y in range(y_dim):
        for x in range(x_dim - 1):
            a = _node_id(x, y, x_dim)
            b = _node_id(x + 1, y, x_dim)
            edges.append((a, b))
    # Also y-direction edges for 2D
    for y in range(y_dim - 1):
        for x in range(x_dim):
            a = _node_id(x, y, x_dim)
            b = _node_id(x, y + 1, x_dim)
            edges.append((a, b))

    # Declare link logic nets for each undirected edge (a, b)
    for a, b in edges:
        w(f"    logic                  link_req_{a}to{b}_valid, link_req_{b}to{a}_valid;")
        w(f"    logic [FLIT_WIDTH-1:0] link_req_{a}to{b}_flit,  link_req_{b}to{a}_flit;")
        w(f"    logic                  link_req_{a}to{b}_credit, link_req_{b}to{a}_credit;  // pulse")
        w(f"    logic                  link_rsp_{a}to{b}_valid, link_rsp_{b}to{a}_valid;")
        w(f"    logic [FLIT_WIDTH-1:0] link_rsp_{a}to{b}_flit,  link_rsp_{b}to{a}_flit;")
        w(f"    logic                  link_rsp_{a}to{b}_credit, link_rsp_{b}to{a}_credit;  // pulse")
    w("")

    # For each node, instantiate router_wrap and wire its link ports.
    # For a 1D mesh:
    #   node0's OUT direction: toward node1 (0to1 net)
    #   node0's IN  direction: from node1  (1to0 net)
    #   node1's OUT direction: toward node0 (1to0 net)
    #   node1's IN  direction: from node0  (0to1 net)
    # router_wrap link port naming (from the original):
    #   link_req_out_valid, link_req_out_flit, link_req_out_credit (credit received from peer)
    #   link_req_in_valid,  link_req_in_flit,  link_req_in_credit  (credit sent to peer)
    # Credit direction: credit for data flowing A→B returns on the B→A net.
    #   link_req_out_credit of node0 = link_req_1to0_credit (credit node0 gets back)
    #   link_req_in_credit  of node0 = link_req_0to1_credit (credit node0 sends to node1)

    # Build a per-node link port map. For S0 (linear mesh), each node has at most
    # one "east" neighbour and one "west" neighbour. We only wire the one link each node has.
    # For simplicity, since router_wrap has exactly one link port pair (REQ+RSP in/out),
    # we connect it to the single neighbour (either east or west in a 2-node mesh).

    # For a general 1D mesh:
    #   Node 0:  only east link (to node 1). Out net = 0to1, in net = 1to0.
    #   Node n-1: only west link (from node n-2). Out net = (n-1)to(n-2), in net = (n-2)to(n-1).
    #   Middle nodes: two links. (S0: not applicable for 2-node mesh)
    # For the 2-node case, each node has exactly 1 link.

    for i in ids:
        r_ctx = _ctx_vars(i)[0]
        # Determine which edge this node connects to.
        # For a 1D mesh: node i connects to node i+1 (if exists) and node i-1 (if exists).
        # For the 2-node case: node 0 → east=(0,1); node 1 → west=(0,1) reversed.
        # router_wrap has a single link port pair; for S0 we always connect to the one edge.
        east_edge = next(((a, b) for a, b in edges if a == i), None)
        west_edge = next(((a, b) for a, b in edges if b == i), None)

        # For S0 (2-node), each node has exactly one edge.
        # The router_wrap's link_*_out is the node's outbound (toward its neighbour).
        # Node 0: east edge (0,1). Out=0to1, In=1to0.
        # Node 1: it's on the (0,1) edge as 'b'. Out=1to0, In=0to1.

        if east_edge is not None:
            a, b = east_edge
            out_valid = f"link_req_{a}to{b}_valid"
            out_flit  = f"link_req_{a}to{b}_flit"
            out_credit_recv = f"link_req_{b}to{a}_credit"  # credit node a gets from b
            in_valid  = f"link_req_{b}to{a}_valid"
            in_flit   = f"link_req_{b}to{a}_flit"
            in_credit_send  = f"link_req_{a}to{b}_credit"  # credit node a returns to b
            rsp_out_valid   = f"link_rsp_{a}to{b}_valid"
            rsp_out_flit    = f"link_rsp_{a}to{b}_flit"
            rsp_out_credit_recv = f"link_rsp_{b}to{a}_credit"
            rsp_in_valid    = f"link_rsp_{b}to{a}_valid"
            rsp_in_flit     = f"link_rsp_{b}to{a}_flit"
            rsp_in_credit_send  = f"link_rsp_{a}to{b}_credit"
            out_comment = f"// REQ link: node{a} OUT -> {a}to{b} data; node{a} IN <- {b}to{a} data."
            rsp_comment = f"// RSP link: mirrored."
        elif west_edge is not None:
            a, b = west_edge  # a < b; current node = b
            # Node b's out is b→a (reversed direction on the edge)
            out_valid = f"link_req_{b}to{a}_valid"
            out_flit  = f"link_req_{b}to{a}_flit"
            out_credit_recv = f"link_req_{a}to{b}_credit"  # credit node b gets from a
            in_valid  = f"link_req_{a}to{b}_valid"
            in_flit   = f"link_req_{a}to{b}_flit"
            in_credit_send  = f"link_req_{b}to{a}_credit"  # credit node b returns to a
            rsp_out_valid   = f"link_rsp_{b}to{a}_valid"
            rsp_out_flit    = f"link_rsp_{b}to{a}_flit"
            rsp_out_credit_recv = f"link_rsp_{a}to{b}_credit"
            rsp_in_valid    = f"link_rsp_{a}to{b}_valid"
            rsp_in_flit     = f"link_rsp_{a}to{b}_flit"
            rsp_in_credit_send  = f"link_rsp_{b}to{a}_credit"
            out_comment = f"// REQ link: node{b} OUT -> {b}to{a} data; node{b} IN <- {a}to{b} data."
            rsp_comment = "// RSP link: mirrored."
        else:
            # Isolated node (no edges) — should not happen for a connected mesh.
            raise ValueError(f"Node {i} has no edges in the topology")

        w(f"    router_wrap #(")
        w(f"        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)")
        w(f"    ) u_router_{i} (")
        w(f"        .clk_i(clk_i),")
        w(f"        .rst_ni(rst_ni),")
        w(f"        .ctx_i({r_ctx}),")
        w(f"        .noc_nmu_i(node{i}_nmu.miso),")
        w(f"        .noc_nsu_o(node{i}_nsu.mosi),")
        w(f"        {out_comment}")
        w(f"        .link_req_out_valid({out_valid}),")
        w(f"        .link_req_out_flit({out_flit}),")
        w(f"        .link_req_out_credit({out_credit_recv}),  // credit for node{i}'s sent data")
        w(f"        .link_req_in_valid({in_valid}),")
        w(f"        .link_req_in_flit({in_flit}),")
        w(f"        .link_req_in_credit({in_credit_send}),   // credit node{i} returns to peer")
        w(f"        {rsp_comment}")
        w(f"        .link_rsp_out_valid({rsp_out_valid}),")
        w(f"        .link_rsp_out_flit({rsp_out_flit}),")
        w(f"        .link_rsp_out_credit({rsp_out_credit_recv}),")
        w(f"        .link_rsp_in_valid({rsp_in_valid}),")
        w(f"        .link_rsp_in_flit({rsp_in_flit}),")
        w(f"        .link_rsp_in_credit({rsp_in_credit_send})")
        w(f"    );")
        w(f"")

    # ------------------------------------------------------------------
    # PMU monitors
    # ------------------------------------------------------------------
    w("    // -------------------------------------------------------------------------")
    w("    // PMU monitors — passive; no drives")
    w("    // -------------------------------------------------------------------------")
    w("    // AXI slot monitors: one per node × {manager, subordinate} edge.")

    for i in ids:
        # manager monitor at node i watches master_nmu_axi_i
        w(f"    axi_perf_monitor #(")
        w(f'        .SLOT_NAME("node{i}.manager"), .ID_W($bits(master_nmu_axi_{i}.awid))')
        w(f"    ) u_perf_mgr_{i} (")
        w(f"        .clk_i, .rst_ni,")
        w(f"        .awvalid(master_nmu_axi_{i}.awvalid), .awready(master_nmu_axi_{i}.awready),")
        w(f"        .awid(master_nmu_axi_{i}.awid),       .awaddr(master_nmu_axi_{i}.awaddr),")
        w(f"        .awlen(master_nmu_axi_{i}.awlen),     .awsize(master_nmu_axi_{i}.awsize),")
        w(f"        .wvalid(master_nmu_axi_{i}.wvalid),   .wready(master_nmu_axi_{i}.wready),")
        w(f"        .bvalid(master_nmu_axi_{i}.bvalid),   .bready(master_nmu_axi_{i}.bready),")
        w(f"        .bid(master_nmu_axi_{i}.bid),")
        w(f"        .arvalid(master_nmu_axi_{i}.arvalid), .arready(master_nmu_axi_{i}.arready),")
        w(f"        .arid(master_nmu_axi_{i}.arid),       .araddr(master_nmu_axi_{i}.araddr),")
        w(f"        .arlen(master_nmu_axi_{i}.arlen),     .arsize(master_nmu_axi_{i}.arsize),")
        w(f"        .rvalid(master_nmu_axi_{i}.rvalid),   .rready(master_nmu_axi_{i}.rready),")
        w(f"        .rlast(master_nmu_axi_{i}.rlast),     .rid(master_nmu_axi_{i}.rid)")
        w(f"    );")
        w(f"")
        # subordinate monitor at node i watches nsu_slave_axi_i
        w(f"    axi_perf_monitor #(")
        w(f'        .SLOT_NAME("node{i}.subordinate"), .ID_W($bits(nsu_slave_axi_{i}.awid))')
        w(f"    ) u_perf_sub_{i} (")
        w(f"        .clk_i, .rst_ni,")
        w(f"        .awvalid(nsu_slave_axi_{i}.awvalid), .awready(nsu_slave_axi_{i}.awready),")
        w(f"        .awid(nsu_slave_axi_{i}.awid),       .awaddr(nsu_slave_axi_{i}.awaddr),")
        w(f"        .awlen(nsu_slave_axi_{i}.awlen),     .awsize(nsu_slave_axi_{i}.awsize),")
        w(f"        .wvalid(nsu_slave_axi_{i}.wvalid),   .wready(nsu_slave_axi_{i}.wready),")
        w(f"        .bvalid(nsu_slave_axi_{i}.bvalid),   .bready(nsu_slave_axi_{i}.bready),")
        w(f"        .bid(nsu_slave_axi_{i}.bid),")
        w(f"        .arvalid(nsu_slave_axi_{i}.arvalid), .arready(nsu_slave_axi_{i}.arready),")
        w(f"        .arid(nsu_slave_axi_{i}.arid),       .araddr(nsu_slave_axi_{i}.araddr),")
        w(f"        .arlen(nsu_slave_axi_{i}.arlen),     .arsize(nsu_slave_axi_{i}.arsize),")
        w(f"        .rvalid(nsu_slave_axi_{i}.rvalid),   .rready(nsu_slave_axi_{i}.rready),")
        w(f"        .rlast(nsu_slave_axi_{i}.rlast),     .rid(nsu_slave_axi_{i}.rid)")
        w(f"    );")
        w(f"")

    w("    // Inter-router link monitors: valid paired with credit from the OPPOSITE direction")
    w("    // (credit for data flowing 0→1 returns on the 1→0 net, and vice versa).")
    for a, b in edges:
        w(f"    link_perf_monitor #(")
        w(f'        .LINK_NAME("req_{a}to{b}"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)')
        w(f"    ) u_perf_link_req{a}{b} (")
        w(f"        .clk_i, .rst_ni,")
        w(f"        .valid(link_req_{a}to{b}_valid), .credit_pulse(link_req_{b}to{a}_credit)")
        w(f"    );")
        w(f"")
        w(f"    link_perf_monitor #(")
        w(f'        .LINK_NAME("req_{b}to{a}"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)')
        w(f"    ) u_perf_link_req{b}{a} (")
        w(f"        .clk_i, .rst_ni,")
        w(f"        .valid(link_req_{b}to{a}_valid), .credit_pulse(link_req_{a}to{b}_credit)")
        w(f"    );")
        w(f"")
        w(f"    link_perf_monitor #(")
        w(f'        .LINK_NAME("rsp_{a}to{b}"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)')
        w(f"    ) u_perf_link_rsp{a}{b} (")
        w(f"        .clk_i, .rst_ni,")
        w(f"        .valid(link_rsp_{a}to{b}_valid), .credit_pulse(link_rsp_{b}to{a}_credit)")
        w(f"    );")
        w(f"")
        w(f"    link_perf_monitor #(")
        w(f'        .LINK_NAME("rsp_{b}to{a}"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)')
        w(f"    ) u_perf_link_rsp{b}{a} (")
        w(f"        .clk_i, .rst_ni,")
        w(f"        .valid(link_rsp_{b}to{a}_valid), .credit_pulse(link_rsp_{a}to{b}_credit)")
        w(f"    );")
        w(f"")

    # ------------------------------------------------------------------
    # Perf instrumentation
    # ------------------------------------------------------------------
    w("    // -------------------------------------------------------------------------")
    w("    // Perf instrumentation — sample every rising edge; dump on final")
    w("    // -------------------------------------------------------------------------")
    w('    import "DPI-C" context function void cmodel_perf_sample_tick();')
    w('    import "DPI-C" context function void cmodel_perf_set_run(input string scenario,')
    w('                                                             input longint total_cyc);')
    w('    import "DPI-C" context function void cmodel_perf_dump(input string path);')
    w("")
    w('    string        perf_out_path = "perf.json";')
    w('    string        perf_scn      = "";')
    w("    int unsigned  perf_cycle    = 0;")
    w("    initial begin")
    w('        void\'($value$plusargs("perf_out=%s", perf_out_path));')
    w('        void\'($value$plusargs("perf_scenario=%s", perf_scn));')
    w("    end")
    w("    always @(posedge clk_i) begin")
    w("        cmodel_perf_sample_tick();")
    w("        perf_cycle = perf_cycle + 1;")
    w("    end")
    w("")
    w("    final begin")
    w("        cmodel_perf_set_run(perf_scn, longint'(perf_cycle));")
    w("        cmodel_perf_dump(perf_out_path);")
    w("        cmodel_finalize();")
    w("    end")
    w("")
    w("    // FSDB waveform dump (VCS only; +define+FSDB_DUMP)")
    w("`ifdef FSDB_DUMP")
    w("    initial begin")
    w("        string fsdb_path;")
    w("        if (!$value$plusargs(\"fsdb=%s\", fsdb_path))")
    w('            fsdb_path = "dump.fsdb";')
    w("        $fsdbDumpfile(fsdb_path);")
    w("        $fsdbDumpvars(0, tb_top);")
    w("    end")
    w("`endif")
    w("")

    # ------------------------------------------------------------------
    # Exit logic — PASS guard
    # ------------------------------------------------------------------
    w("    // -------------------------------------------------------------------------")
    w("    // Exit logic — non-vacuous PASS guard")
    w("    // -------------------------------------------------------------------------")
    w("    // cmodel_done() signals scenario completion via DPI.")
    w(f"    // PASS requires a non-vacuous run: scoreboard clean AND all {n} masters created")
    w("    // AND at least one read actually checked (so a write-only / no-op run fails).")
    w("    always @(posedge clk_i) begin")
    w("        /* verilator lint_off WIDTHTRUNC */")
    w("        if (rst_ni && (cmodel_done() != 0)) begin")
    w(f"            if (cmodel_scoreboard_clean() != 0 &&")
    w(f"                cmodel_master_count() == {n} && cmodel_reads_checked() > 0) begin")
    w("        /* verilator lint_on WIDTHTRUNC */")
    w('                $display("PASS: scenario complete, scoreboard clean");')
    w("                cmodel_dump_scoreboard();")
    w("                $finish(0);")
    w("            end else begin")
    w('                $display("FAIL: scoreboard mismatch or vacuous run (masters=%0d reads=%0d)",')
    w("                         cmodel_master_count(), cmodel_reads_checked());")
    w("                cmodel_dump_scoreboard();")
    w('                $fatal(1, "tb_top: bidirectional run failed");')
    w("            end")
    w("        end")
    w("    end")
    w("")
    w("    // -------------------------------------------------------------------------")
    w("    // Centralized DPI error poll (T1.4)")
    w("    // -------------------------------------------------------------------------")
    w("    // Wraps no longer call cmodel_finalize individually; this single block")
    w("    // owns the fatal-exit path. Previously each wrap had its own error_check")
    w("    // block that called cmodel_finalize on non-zero, which risked a race where")
    w("    // multiple wraps tried to destruct the C++ model in the same delta cycle.")
    w('    import "DPI-C" context function int cmodel_check_error(output string msg);')
    w("")
    w("    always_ff @(posedge clk_i) begin")
    w("        /* verilator lint_off WIDTHTRUNC */")
    w("        if (rst_ni) begin")
    w("            string dpi_err_msg;")
    w("            int    dpi_err_code;")
    w("            dpi_err_code = cmodel_check_error(dpi_err_msg);")
    w("            if (dpi_err_code != 0) begin")
    w('                $display("[tb_top] DPI fatal (code=%0d): %s",')
    w("                         dpi_err_code, dpi_err_msg);")
    w("                cmodel_dump_scoreboard();")
    w("                cmodel_finalize();")
    w('                $fatal(1, "tb_top: DPI error, simulation aborted");')
    w("            end")
    w("        end")
    w("        /* verilator lint_on WIDTHTRUNC */")
    w("    end")
    w("")
    w("endmodule")
    w("")
    w("`endif  // TB_TOP_SV")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(
        description="Generate tb_top.sv from topology config."
    )
    ap.add_argument("--topology", default="mesh_2x1",
                    help="Topology name (matches sim/topologies/<name>.yaml)")
    ap.add_argument("--out", default=str(ROOT / "sim" / "sv" / "tb_top.sv"),
                    help="Output file path")
    ap.add_argument("--check", action="store_true",
                    help="Drift gate: regenerate and diff vs committed file; exit 1 if different")
    a = ap.parse_args()

    topo = load_topology(a.topology)
    text = emit_tb_top(topo)

    if a.check:
        out_path = Path(a.out)
        if not out_path.exists():
            print(f"DRIFT: {a.out} does not exist (never generated)")
            return 1
        cur = out_path.read_text(encoding="utf-8")
        if cur != text:
            sys.stdout.writelines(difflib.unified_diff(
                cur.splitlines(True),
                text.splitlines(True),
                "committed",
                "regenerated",
            ))
            print("DRIFT: tb_top.sv differs from generator output")
            return 1
        return 0

    Path(a.out).write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
