"""Python half of the two-reader parity gate on the FlooNoC-shaped configs.

sim/tools/address_map.py and c_model's nmu/sam_yaml.hpp expand the same config
file, one at generate time and one at simulation runtime through +sam_config. If
the two expansions diverge, the generated package and the generated stimulus
agree with each other and disagree with the runtime address translator: every
artifact looks self-consistent while traffic decodes to the wrong node. A
passing simulation does not catch that, because it only ever compares the two
halves that agree.

The C++ reader is a header consumed by gtest and by the DPI library, with no
callable interface from Python, so the two sides meet at
sim/configs/sam_rules.golden. This test holds the Python expansion to that file;
ref_model/c_model/tests/nmu/test_sam_config.cpp holds the C++ one to it. Both
compare line for line and in order -- a set comparison would pass on an X-fast
against a Y-fast expansion, which on a square mesh produce the identical set of
bases and transpose every coordinate.

Regenerate the golden with:
    python3 -c "import test_sam_config_parity as t; t.write_golden()"
and read the diff before committing it: a changed line is a changed address map.
"""

import pathlib

import yaml

import address_map

ROOT = pathlib.Path(__file__).resolve().parents[2]
CONFIG_DIR = ROOT / "sim" / "configs"
GOLDEN = CONFIG_DIR / "sam_rules.golden"

# Each new config replaces this topology YAML. The old shape is still the one
# the build and the runtime use; both must describe the same map.
REPLACES = {
    "mesh_2x2": "mesh_2x2_vc1",
    "mesh_2x2_periph": "mesh_2x2_vc1_periph",
    "mesh_4x4": "mesh_4x4_vc1",
    "mesh_4x4_periph4": "mesh_4x4_vc1_periph4",
}


def configs():
    files = sorted(CONFIG_DIR.glob("*.yml"))
    assert files, f"expected the FlooNoC-shaped configs in {CONFIG_DIR}"
    return files


def rule_line(name, entry):
    """One SAM rule as the golden spells it. Twin of test_sam_config.cpp's rule_line."""
    return (f"{name} {entry['space']} {entry['base']:#x} {entry['size']:#x} "
            f"{entry['dst_id']:#x} {entry.get('port', 0)}")


def rule_lines():
    out = []
    for path in configs():
        _bases, entries = address_map.pack_document(yaml.safe_load(path.read_text()))
        out += [rule_line(path.stem, e) for e in entries]
    return out


def golden_lines():
    return [ln for ln in GOLDEN.read_text().splitlines()
            if ln.strip() and not ln.startswith("#")]


def write_golden():
    header = (
        "# SAM rules expanded from sim/configs/*.yml, one line per rule, in order:\n"
        "#   <config> <space> <base> <size> <dst_id> <port>\n"
        "# The meeting point of the two readers that must expand a config identically --\n"
        "# sim/tools/address_map.py (generate time) and nmu/sam_yaml.hpp (simulation\n"
        "# runtime, via +sam_config). test_sam_config_parity.py holds the first to this\n"
        "# file and ref_model/c_model/tests/nmu/test_sam_config.cpp the second.\n"
        "# Generated by test_sam_config_parity.write_golden(); a changed line is a\n"
        "# changed address map.\n")
    GOLDEN.write_text(header + "\n".join(rule_lines()) + "\n")


def test_python_expansion_matches_the_golden():
    assert rule_lines() == golden_lines()


def test_each_config_expands_to_the_map_of_the_topology_yaml_it_replaces():
    """The new shape and the old one describe the same map, rule for rule.

    Independent of the golden: it compares the two readers' *input* formats
    through one reader, where the golden compares one format through two readers.
    """
    for path in configs():
        old = ROOT / "sim" / "topologies" / f"{REPLACES[path.stem]}.yaml"
        _b, new_entries = address_map.pack_document(yaml.safe_load(path.read_text()))
        _b, old_entries = address_map.pack_document(yaml.safe_load(old.read_text()))
        assert ([rule_line(path.stem, e) for e in new_entries]
                == [rule_line(path.stem, e) for e in old_entries]), path.stem
