import csv
import json
import re

import pytest

import perf_report as pr


_TRAFFIC_COUNTS = {
    "broadcast_row": (4, 16, 4 * 16, 16 * 16, 4),
    "broadcast_col": (4, 16, 4 * 16, 16 * 16, 4),
    "broadcast_submesh": (4, 16, 4 * 16, 16 * 16, 4),
    "broadcast_global": (1, 16, 1 * 16, 16 * 16, 1),
    "gather_global_root0": (15, 1, 15 * 16, 15 * 16, 15),
    "gather_submesh": (12, 4, 12 * 16, 12 * 16, 12),
    "alltoall": (16, 16, 16 * 15 * 16, 16 * 15 * 16, 16),
    "neighbor_exchange": (16, 16, 48 * 16, 48 * 16, 16),
    "pipeline": (15, 15, 15 * 16, 15 * 16, 15),
    "many_to_many": (16, 16, 16 * 4 * 16, 16 * 4 * 16, 16),
}
_BROADCAST_FANOUT = {
    "broadcast_row": 4,
    "broadcast_col": 4,
    "broadcast_submesh": 4,
    "broadcast_global": 16,
}


# Captured from four deterministic 4x4, AxLEN=0, one-round, no-stall runs.
# Keep these dictionaries literal: they are the independent emitted-counter
# oracle for pattern_metrics.ai_resource_flits(), not values generated by it.
_PIPELINE_WRITE_COUNTERS = {
    "dat_0to1": 2, "dat_10to11": 2, "dat_11to15": 2,
    "dat_13to12": 2, "dat_14to13": 2, "dat_15to14": 2,
    "dat_1to2": 2, "dat_2to3": 2, "dat_3to7": 2,
    "dat_4to8": 2, "dat_5to4": 2, "dat_6to5": 2,
    "dat_7to6": 2, "dat_8to9": 2, "dat_9to10": 2,
    "dat_eject_1": 2, "dat_eject_10": 2, "dat_eject_11": 2,
    "dat_eject_12": 2, "dat_eject_13": 2, "dat_eject_14": 2,
    "dat_eject_15": 2, "dat_eject_2": 2, "dat_eject_3": 2,
    "dat_eject_4": 2, "dat_eject_5": 2, "dat_eject_6": 2,
    "dat_eject_7": 2, "dat_eject_8": 2, "dat_eject_9": 2,
    "dat_inject_0": 2, "dat_inject_1": 2, "dat_inject_10": 2,
    "dat_inject_11": 2, "dat_inject_13": 2, "dat_inject_14": 2,
    "dat_inject_15": 2, "dat_inject_2": 2, "dat_inject_3": 2,
    "dat_inject_4": 2, "dat_inject_5": 2, "dat_inject_6": 2,
    "dat_inject_7": 2, "dat_inject_8": 2, "dat_inject_9": 2,
    "rsp_10to9": 1, "rsp_11to10": 1, "rsp_12to13": 1,
    "rsp_13to14": 1, "rsp_14to15": 1, "rsp_15to11": 1,
    "rsp_1to0": 1, "rsp_2to1": 1, "rsp_3to2": 1,
    "rsp_4to5": 1, "rsp_5to6": 1, "rsp_6to7": 1,
    "rsp_7to3": 1, "rsp_8to4": 1, "rsp_9to8": 1,
    "rsp_eject_0": 1, "rsp_eject_1": 1, "rsp_eject_10": 1,
    "rsp_eject_11": 1, "rsp_eject_13": 1, "rsp_eject_14": 1,
    "rsp_eject_15": 1, "rsp_eject_2": 1, "rsp_eject_3": 1,
    "rsp_eject_4": 1, "rsp_eject_5": 1, "rsp_eject_6": 1,
    "rsp_eject_7": 1, "rsp_eject_8": 1, "rsp_eject_9": 1,
    "rsp_inject_1": 1, "rsp_inject_10": 1, "rsp_inject_11": 1,
    "rsp_inject_12": 1, "rsp_inject_13": 1, "rsp_inject_14": 1,
    "rsp_inject_15": 1, "rsp_inject_2": 1, "rsp_inject_3": 1,
    "rsp_inject_4": 1, "rsp_inject_5": 1, "rsp_inject_6": 1,
    "rsp_inject_7": 1, "rsp_inject_8": 1, "rsp_inject_9": 1,
}

_PIPELINE_READ_COUNTERS = {
    "dat_0to1": 1, "dat_10to11": 1, "dat_11to15": 1,
    "dat_13to12": 1, "dat_14to13": 1, "dat_15to14": 1,
    "dat_1to2": 1, "dat_2to3": 1, "dat_3to7": 1,
    "dat_4to8": 1, "dat_5to4": 1, "dat_6to5": 1,
    "dat_7to6": 1, "dat_8to9": 1, "dat_9to10": 1,
    "dat_eject_1": 1, "dat_eject_10": 1, "dat_eject_11": 1,
    "dat_eject_12": 1, "dat_eject_13": 1, "dat_eject_14": 1,
    "dat_eject_15": 1, "dat_eject_2": 1, "dat_eject_3": 1,
    "dat_eject_4": 1, "dat_eject_5": 1, "dat_eject_6": 1,
    "dat_eject_7": 1, "dat_eject_8": 1, "dat_eject_9": 1,
    "dat_inject_0": 1, "dat_inject_1": 1, "dat_inject_10": 1,
    "dat_inject_11": 1, "dat_inject_13": 1, "dat_inject_14": 1,
    "dat_inject_15": 1, "dat_inject_2": 1, "dat_inject_3": 1,
    "dat_inject_4": 1, "dat_inject_5": 1, "dat_inject_6": 1,
    "dat_inject_7": 1, "dat_inject_8": 1, "dat_inject_9": 1,
    "req_10to9": 1, "req_11to10": 1, "req_12to13": 1,
    "req_13to14": 1, "req_14to15": 1, "req_15to11": 1,
    "req_1to0": 1, "req_2to1": 1, "req_3to2": 1,
    "req_4to5": 1, "req_5to6": 1, "req_6to7": 1,
    "req_7to3": 1, "req_8to4": 1, "req_9to8": 1,
    "req_eject_0": 1, "req_eject_1": 1, "req_eject_10": 1,
    "req_eject_11": 1, "req_eject_13": 1, "req_eject_14": 1,
    "req_eject_15": 1, "req_eject_2": 1, "req_eject_3": 1,
    "req_eject_4": 1, "req_eject_5": 1, "req_eject_6": 1,
    "req_eject_7": 1, "req_eject_8": 1, "req_eject_9": 1,
    "req_inject_1": 1, "req_inject_10": 1, "req_inject_11": 1,
    "req_inject_12": 1, "req_inject_13": 1, "req_inject_14": 1,
    "req_inject_15": 1, "req_inject_2": 1, "req_inject_3": 1,
    "req_inject_4": 1, "req_inject_5": 1, "req_inject_6": 1,
    "req_inject_7": 1, "req_inject_8": 1, "req_inject_9": 1,
}

_BROADCAST_HARDWARE_COUNTERS = {
    "dat_0to1": 2, "dat_0to4": 2, "dat_10to14": 2,
    "dat_11to15": 2, "dat_1to2": 2, "dat_1to5": 2,
    "dat_2to3": 2, "dat_2to6": 2, "dat_3to7": 2,
    "dat_4to8": 2, "dat_5to9": 2, "dat_6to10": 2,
    "dat_7to11": 2, "dat_8to12": 2, "dat_9to13": 2,
    "dat_eject_0": 2, "dat_eject_1": 2, "dat_eject_10": 2,
    "dat_eject_11": 2, "dat_eject_12": 2, "dat_eject_13": 2,
    "dat_eject_14": 2, "dat_eject_15": 2, "dat_eject_2": 2,
    "dat_eject_3": 2, "dat_eject_4": 2, "dat_eject_5": 2,
    "dat_eject_6": 2, "dat_eject_7": 2, "dat_eject_8": 2,
    "dat_eject_9": 2, "dat_inject_0": 2,
    "rsp_10to9": 1, "rsp_11to10": 1, "rsp_12to8": 1,
    "rsp_13to12": 1, "rsp_14to13": 1, "rsp_15to14": 1,
    "rsp_1to0": 1, "rsp_2to1": 1, "rsp_3to2": 1,
    "rsp_4to0": 1, "rsp_5to4": 1, "rsp_6to5": 1,
    "rsp_7to6": 1, "rsp_8to4": 1, "rsp_9to8": 1,
    "rsp_eject_0": 1, "rsp_inject_0": 1, "rsp_inject_1": 1,
    "rsp_inject_10": 1, "rsp_inject_11": 1, "rsp_inject_12": 1,
    "rsp_inject_13": 1, "rsp_inject_14": 1, "rsp_inject_15": 1,
    "rsp_inject_2": 1, "rsp_inject_3": 1, "rsp_inject_4": 1,
    "rsp_inject_5": 1, "rsp_inject_6": 1, "rsp_inject_7": 1,
    "rsp_inject_8": 1, "rsp_inject_9": 1,
}

_BROADCAST_REPEATED_UNICAST_COUNTERS = {
    "dat_0to1": 24, "dat_0to4": 6, "dat_10to14": 2,
    "dat_11to15": 2, "dat_1to2": 16, "dat_1to5": 6,
    "dat_2to3": 8, "dat_2to6": 6, "dat_3to7": 6,
    "dat_4to8": 4, "dat_5to9": 4, "dat_6to10": 4,
    "dat_7to11": 4, "dat_8to12": 2, "dat_9to13": 2,
    "dat_eject_1": 2, "dat_eject_10": 2, "dat_eject_11": 2,
    "dat_eject_12": 2, "dat_eject_13": 2, "dat_eject_14": 2,
    "dat_eject_15": 2, "dat_eject_2": 2, "dat_eject_3": 2,
    "dat_eject_4": 2, "dat_eject_5": 2, "dat_eject_6": 2,
    "dat_eject_7": 2, "dat_eject_8": 2, "dat_eject_9": 2,
    "dat_inject_0": 30,
    "rsp_10to9": 2, "rsp_11to10": 1, "rsp_12to8": 4,
    "rsp_13to12": 3, "rsp_14to13": 2, "rsp_15to14": 1,
    "rsp_1to0": 3, "rsp_2to1": 2, "rsp_3to2": 1,
    "rsp_4to0": 12, "rsp_5to4": 3, "rsp_6to5": 2,
    "rsp_7to6": 1, "rsp_8to4": 8, "rsp_9to8": 3,
    "rsp_eject_0": 15,
    "rsp_inject_1": 1, "rsp_inject_10": 1, "rsp_inject_11": 1,
    "rsp_inject_12": 1, "rsp_inject_13": 1, "rsp_inject_14": 1,
    "rsp_inject_15": 1, "rsp_inject_2": 1, "rsp_inject_3": 1,
    "rsp_inject_4": 1, "rsp_inject_5": 1, "rsp_inject_6": 1,
    "rsp_inject_7": 1, "rsp_inject_8": 1, "rsp_inject_9": 1,
}

_EMITTED_COUNTER_FIXTURES = (
    ("directed Write", "pipeline", "write", None, 15, 15,
     _PIPELINE_WRITE_COUNTERS),
    ("directed Read", "pipeline", "read", None, 15, 15,
     _PIPELINE_READ_COUNTERS),
    ("hardware multicast", "broadcast_global", "write", "hardware", 1, 16,
     _BROADCAST_HARDWARE_COUNTERS),
    ("repeated unicast", "broadcast_global", "write", "repeated_unicast", 16, 16,
     _BROADCAST_REPEATED_UNICAST_COUNTERS),
)


def _write_result(root, direction, mapping, outstanding, bandwidth=None,
                   latency=None, vc=2, depth=8, seed=1, category="baseline",
                   r_rob_depth=128, max_txns_per_id=32, burst_beats=64,
                   transactions_per_flow=1, multicast_mode=None,
                   completion_cycles=1000):
    pattern = mapping.split("_", 1)[0]
    if mapping in ("alltoall", "neighbor_exchange", "pipeline", "many_to_many"):
        pattern = mapping
    mode_tag = f"_{multicast_mode}" if multicast_mode else ""
    burst_tag = f"_bl{burst_beats}" if category == "burst" else ""
    run = root / category / f"{mapping}_{direction}_o{outstanding}_s{seed}_v{vc}_b{depth}{mode_tag}"
    run = run.with_name(run.name + burst_tag)
    run.mkdir(parents=True, exist_ok=True)
    bandwidth = bandwidth if bandwidth is not None else 100.0 * min(outstanding, 4)
    latency = latency if latency is not None else 40.0 + outstanding
    producers, consumers, requests, deliveries, initiators = _TRAFFIC_COUNTS[mapping]
    requests *= transactions_per_flow
    deliveries *= transactions_per_flow
    multicast_mode = (multicast_mode or
                      ("hardware" if mapping.startswith("broadcast_") else ""))
    if multicast_mode == "repeated_unicast":
        requests = deliveries
    row = {
        "topology": "mesh_4x4", "vc": str(vc),
        "router_vc_depth": str(depth), "ni_dat_rx_vc_depth": str(depth),
        "pattern": pattern, "traffic_mapping": mapping,
        "measurement_mode": "outstanding", "direction": direction,
        "data_producers": str(producers), "consumers": str(consumers),
        "axi_initiators": str(initiators), "source_requests": str(requests),
        "payload_deliveries": str(deliveries), "rounds": "16",
        "multicast_mode": multicast_mode,
        "destinations_per_source": str(_BROADCAST_FANOUT.get(mapping, "")),
        "transactions_per_flow": str(transactions_per_flow),
        "bytes_per_flow_round": str(burst_beats * transactions_per_flow * 64),
        "source_outstanding_depth": str(outstanding),
        "source_outstanding_hwm": str(outstanding), "seed": str(seed),
        "max_unique_ids": "8", "max_outstanding": "32",
        "r_rob_depth": str(r_rob_depth),
        "max_txns_per_id": str(max_txns_per_id), "ids_per_initiator": "1",
        "burst_length": str(burst_beats - 1), "burst_beats": str(burst_beats),
        "bytes_per_beat": "64", "transaction_bytes": str(burst_beats * 64),
        "completion_cycles": str(completion_cycles),
        "completion_latency_cycles": str(latency),
        "delivered_payload_bytes_per_cycle": str(bandwidth),
        "checker_status": "PASS", "busiest_dat_link_utilization_pct": "80.0",
        "dat_links_total": "48", "dat_links_ge_25_pct": "12",
        "dat_links_ge_50_pct": "8", "dat_links_ge_75_pct": "4",
        "dat_links_ge_90_pct": "0",
        "nmu_read_slot_hwm_beats": str(min(r_rob_depth, outstanding * 64)),
        "nmu_order_list_hwm_transactions": str(min(max_txns_per_id, outstanding)),
    }
    with (run / "result.csv").open("w", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(row))
        writer.writeheader()
        writer.writerow(row)
    mode = multicast_mode or None
    resources = pr.pm.ai_resource_flits(
        mapping, direction, burst_beats, 16 * transactions_per_flow, mode)
    links = [{"name": name, "flit_count": count, "stall_cyc": 0}
             for name, count in resources.items()]
    (run / "perf.json").write_text(json.dumps({"noc": {"links": links}}))
    return run / "result.csv"


def _complete_baseline(root):
    for direction, mappings in (("write", pr.WRITE_MAPPINGS),
                                ("read", pr.READ_MAPPINGS)):
        for mapping in mappings:
            _write_result(root, direction, mapping, 32)


def _complete_tradeoff_config(root, vc, depth, bandwidth_scale=1.0,
                              latency_scale=1.0):
    stress_rows = (
        ("write", "broadcast_global"),
        ("write", "gather_global_root0"),
        ("read", "gather_global_root0"),
        ("write", "many_to_many"),
        ("read", "many_to_many"),
    )
    for direction, mapping in stress_rows:
        outstanding = 32
        _write_result(
            root, direction, mapping, outstanding,
            bandwidth=400.0 * bandwidth_scale,
            latency=72.0 * latency_scale,
            vc=vc, depth=depth, category=f"tradeoff/v{vc}_b{depth}",
        )


def _complete_channel_compare(root):
    for mapping, architecture in (("2-channel", "rr"), ("3-channel", "rrd")):
        for case, latency in (("write", 4000 if architecture == "rr" else 1000),
                              ("read", 3600 if architecture == "rr" else 3300)):
            run = root / "rr_vs_rrd" / f"{architecture}_{case}"
            run.mkdir(parents=True)
            row = {
                "channel_mapping": mapping, "channel_case": case,
                "control_mean_latency_cycles": str(latency), "seed": "1",
                "data_bursts_per_flow": "32", "data_beats_per_flow": "8192",
                "shared_directed_edge": "1to2", "control_resource": "req_1to2",
                "background_resource": (
                    "dat_1to2" if architecture == "rrd" else
                    "req_1to2"),
                "overlap_status": "PASS",
            }
            with (run / "result.csv").open("w", newline="") as stream:
                writer = csv.DictWriter(stream, fieldnames=list(row))
                writer.writeheader()
                writer.writerow(row)


def test_report_uses_one_common_metric_table_without_rate_terms(tmp_path):
    _complete_baseline(tmp_path)
    text = pr.report(tmp_path)
    assert re.findall(r"^## .+$", text, re.M) == [
        "## 1. 測試設定與量測方法",
        "## 2. MHA、MoE 與 Pipeline Traffic Models",
        "## 3. Performance Results",
        "## 4. Burst Length Characterization",
        "## 5. Multicast vs Repeated Unicast",
        "## 6. VC 與 Buffer Trade-off",
        "## 7. RR vs RRD",
        "## 8. Compute Overlap Coverage",
    ]
    assert "Latency<br>(cycles/transaction)" not in text
    assert "| Traffic Model | Direction | Ideal Throughput Bound (B/cycle) | Accepted Throughput (B/cycle) | Throughput Efficiency (%) |" in text
    assert "Throughput<br>(B/cycle)" not in text
    assert "Completion Time<br>(cycles/run)" not in text
    assert "Peak Link Utilization<br>(%)" not in text
    assert "Loaded Links<br>(>=75%)" not in text
    assert "Knee Outstanding" not in text
    assert "Injection rate" not in text and "Offered load" not in text
    assert "Broadcast | Read" not in text
    assert "Broadcast is Write-only" not in text
    assert "Reference transaction bytes = 64 beats * 64 B/beat = 4096 B" in text
    assert "Transaction bytes = Burst Length * 64 B/beat" in text
    assert "Reference DUT：DAT VCs = 2" in text
    assert "量測流程" in text and "表格解讀" in text
    assert "Throughput Saturation Depth" not in text
    assert "traffic_patterns/broadcast_row.svg" in text
    assert "| Traffic | AI Workload |" in text
    assert "| Traffic Model | AI Workload | Data Movement | Evidence |" not in text
    assert "| All-Gather | MHA |" in text
    assert "All-Reduce" not in text
    assert "[TBD]" in text
    assert "Completion Time = final B completion cycle - common start cycle" in text
    assert "Speedup = Repeated Unicast Completion Time / Multicast Completion Time" in text
    assert "Multicast Injected Flits = Source Count * Rounds * (1 + Burst Length)" in text
    assert ("Repeated Unicast Injected Flits = Source Count * Rounds * "
            "(Fanout - 1) * (1 + Burst Length)") in text
    assert "Row-wise Multicast = 4 * 16 * 65 = 4160 flits" in text
    assert "Global Repeated Unicast = 1 * 16 * 15 * 65 = 15600 flits" in text
    assert "Payload per destination per round = 64 beats * 64 B/beat = 4096 B = 4 KiB" in text
    assert "Payload per destination per run = 4096 B * 16 rounds = 65536 B = 64 KiB" in text
    assert "injected payload per source per run" not in text
    assert "每個 destination 發出一筆獨立 Write transaction" in text
    assert "Neighbor Exchange" not in text
    assert "Gather - Global" not in text
    assert ";" not in text and "；" not in text
    assert "—" not in text and "–" not in text


def test_main_metric_uses_outstanding_32_and_pattern_resource_bound(tmp_path):
    _complete_baseline(tmp_path)
    _write_result(tmp_path, "write", "pipeline", 32, bandwidth=123.0)

    text = pr.report(tmp_path)

    assert "| Pipeline P2P | Write | 945.2 | 123.0 | 13.0 |" in text


def test_fixed_outstanding_32_baseline_is_complete_without_a_sweep(tmp_path):
    _complete_baseline(tmp_path)

    text = pr.report(tmp_path)

    assert "Accepted Throughput (B/cycle)" in text


def test_burst_rows_require_fixed_payload_and_fixed_outstanding(tmp_path):
    for burst_beats in (1, 4, 16, 64):
        _write_result(
            tmp_path, "write", "pipeline", 32, category="burst",
            burst_beats=burst_beats, transactions_per_flow=64 // burst_beats)

    rows = pr.collect_burst_rows(tmp_path / "burst")
    assert [(row["burst_beats"], row["transactions_per_flow"])
            for row in rows] == [(1, 64), (4, 16), (16, 4), (64, 1)]
    assert all(row["bytes_per_flow_round"] == 4096 for row in rows)

    for mapping in pr.BURST_MAPPINGS:
        for direction in (("write",) if mapping.startswith("broadcast_")
                          else ("write", "read")):
            if (mapping, direction) == ("pipeline", "write"):
                continue
            for burst_beats in (1, 4, 16, 64):
                _write_result(
                    tmp_path, direction, mapping, 32, category="burst",
                    burst_beats=burst_beats,
                    transactions_per_flow=64 // burst_beats)
    table = pr._burst_table(pr.collect_burst_rows(tmp_path / "burst"))
    assert "Accepted Throughput (B/cycle)" in table
    assert "Delivered throughput" not in table

    path = next((tmp_path / "burst").rglob("result.csv"))
    row = next(csv.DictReader(path.open()))
    row["bytes_per_flow_round"] = "4032"
    with path.open("w", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(row))
        writer.writeheader()
        writer.writerow(row)
    with pytest.raises(SystemExit, match="4096 B/flow/round"):
        pr.collect_burst_rows(tmp_path / "burst")


def test_multicast_comparison_pairs_hardware_and_repeated_unicast(tmp_path):
    results = []
    for mapping in pr.WRITE_MAPPINGS[:4]:
        for mode in ("hardware", "repeated_unicast"):
            path = _write_result(
                tmp_path, "write", mapping, 32,
                category="multicast_compare", multicast_mode=mode)
            results.append((path, 1500 if mode == "repeated_unicast" else 600))
    for path, completion in results:
        row = next(csv.DictReader(path.open()))
        row["completion_cycles"] = str(completion)
        with path.open("w", newline="") as stream:
            writer = csv.DictWriter(stream, fieldnames=list(row))
            writer.writeheader()
            writer.writerow(row)

    rows = pr.collect_multicast_rows(tmp_path / "multicast_compare")
    assert {row["multicast_mode"] for row in rows} == {
        "hardware", "repeated_unicast"}
    assert {(row["mapping"], row["destination_count"])
            for row in rows} == {
                ("broadcast_row", 4), ("broadcast_col", 4),
                ("broadcast_submesh", 4), ("broadcast_global", 16),
            }
    assert next(row for row in rows if row["multicast_mode"] == "hardware")[
        "source_requests"] < 256
    assert next(row for row in rows if row["multicast_mode"] == "repeated_unicast")[
        "source_requests"] == 256

    text = pr._multicast_table(rows)
    assert "Destination Set" in text
    assert "Fanout" in text
    assert "Multicast Injected Flits" in text
    assert "Repeated Unicast Injected Flits" in text
    assert "Completion Time" in text
    assert "Multicast scope" not in text
    assert "Destination count" not in text
    assert "| Global Multicast | 16 | 1040 | 600 | 15600 | 1500 | 2.50 |" in text
    assert "source requests" not in text.lower()
    assert "throughput" not in text.lower()


def test_report_defines_multicast_fanout_and_injected_flits(tmp_path):
    _complete_baseline(tmp_path)

    text = pr.report(tmp_path)

    assert ("Fanout 包含 source 本身。Local delivery 不經過 mesh link。"
            "Injected Flits 不包含 B／CollectB。") in text


@pytest.mark.parametrize(("field", "value", "message"), [
    ("payload_deliveries", "239", "payload delivery count"),
    ("source_requests", "239", "source request count"),
])
def test_report_rejects_wrong_workload_counts_before_efficiency(
        tmp_path, field, value, message):
    _complete_baseline(tmp_path)
    path = _write_result(tmp_path, "write", "pipeline", 32)
    row = next(csv.DictReader(path.open()))
    row[field] = value
    with path.open("w", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(row))
        writer.writeheader()
        writer.writerow(row)

    with pytest.raises(SystemExit, match=message):
        pr.report(tmp_path)


def test_report_rejects_wrong_emitted_link_count_before_efficiency(tmp_path):
    _complete_baseline(tmp_path)
    path = _write_result(tmp_path, "write", "pipeline", 32)
    perf_path = path.with_name("perf.json")
    perf = json.loads(perf_path.read_text())
    perf["noc"]["links"][0]["flit_count"] += 1
    perf_path.write_text(json.dumps(perf))

    with pytest.raises(SystemExit, match="resource flit counts"):
        pr.report(tmp_path)


def test_report_rejects_missing_source_injection_before_efficiency(tmp_path):
    path = _write_result(tmp_path, "write", "pipeline", 32)
    perf_path = path.with_name("perf.json")
    perf = json.loads(perf_path.read_text())
    perf["noc"]["links"] = [
        link for link in perf["noc"]["links"] if "_inject_" not in link["name"]
    ]
    perf_path.write_text(json.dumps(perf))

    with pytest.raises(SystemExit, match="resource flit counts"):
        pr.collect_rows(tmp_path / "baseline")


@pytest.mark.parametrize(
    ("label", "mapping", "direction", "mode", "requests", "deliveries", "counters"),
    _EMITTED_COUNTER_FIXTURES,
    ids=[fixture[0] for fixture in _EMITTED_COUNTER_FIXTURES],
)
def test_literal_no_stall_emitted_counters_match_and_reject_corruption(
        tmp_path, label, mapping, direction, mode, requests, deliveries, counters):
    assert pr._expected_workload_counts(mapping, 1, mode) == (requests, deliveries)
    assert any("_inject_" in name for name in counters)
    assert any("to" in name for name in counters)
    assert any("_eject_" in name for name in counters)

    perf_path = tmp_path / f"{label.replace(' ', '_')}.json"
    links = [{"name": name, "flit_count": count, "stall_cyc": 0}
             for name, count in counters.items()]
    perf_path.write_text(json.dumps({"noc": {"links": links}}))
    pr._validate_resource_counters(
        perf_path, mapping, direction, burst_beats=1, rounds=1,
        multicast_mode=mode)

    links[0]["flit_count"] += 1
    perf_path.write_text(json.dumps({"noc": {"links": links}}))
    with pytest.raises(SystemExit, match="resource flit counts"):
        pr._validate_resource_counters(
            perf_path, mapping, direction, burst_beats=1, rounds=1,
            multicast_mode=mode)


@pytest.mark.parametrize(("field", "value"), [
    ("checker_status", "FAIL"), ("transaction_bytes", "2048"),
    ("burst_beats", "32"), ("direction", "mixed"),
    ("source_outstanding_depth", "16"), ("source_outstanding_hwm", "33"),
    ("max_txns_per_id", "16"),
])
def test_collection_rejects_nonfixed_o32_maxid32_rows(tmp_path, field, value):
    path = _write_result(tmp_path, "write", "pipeline", 32)
    row = next(csv.DictReader(path.open()))
    row[field] = value
    with path.open("w", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(row))
        writer.writeheader()
        writer.writerow(row)
    with pytest.raises(SystemExit):
        pr.collect_rows(tmp_path / "baseline")


def test_report_rejects_incomplete_baseline(tmp_path):
    _write_result(tmp_path, "write", "pipeline", 32)
    with pytest.raises(SystemExit, match="incomplete"):
        pr.report(tmp_path)


def test_traffic_figures_cover_every_communication_type(tmp_path):
    paths = pr.write_traffic_figures(tmp_path)
    assert {path.stem for path in paths} == set(pr.GALLERY_MAPPINGS)
    assert pr._traffic_roles("gather_submesh")[1] == {5, 6, 9, 10}
    for path in paths:
        svg = path.read_text(encoding="utf-8")
        assert svg.count('class="node"') == 16
        assert "4 x 4 Mesh" in svg
        assert "Source" in svg and "Destination" in svg
        assert re.search(r"[\u4e00-\u9fff]", svg) is None


def test_compute_overlap_requires_an_explicit_pe_budget(tmp_path):
    _complete_baseline(tmp_path)
    text = pr.report(tmp_path)
    assert "PE compute budget = [TBD] cycles/round" in text
    assert "Compute overlap coverage (%) = min(100, PE compute budget / NoC completion cycles * 100)" in text
    assert "PE compute budget 尚未定義，因此不提供數值" in text


def test_tradeoff_pareto_keeps_each_workload_throughput_and_completion_objective(
        tmp_path):
    _complete_baseline(tmp_path)
    stress_rows = (
        ("write", "broadcast_global"),
        ("write", "gather_global_root0"),
        ("read", "gather_global_root0"),
        ("write", "many_to_many"),
        ("read", "many_to_many"),
    )
    metrics = {
        # Cheapest: dominates an aggregate summary, but not either expensive
        # candidate when every cell remains an objective.
        (1, 8): {
            ("write", "broadcast_global"): (400.0, 1000),
            ("write", "gather_global_root0"): (500.0, 900),
        },
        # Survives only because Broadcast Accepted Throughput is higher.
        (2, 16): {
            ("write", "broadcast_global"): (500.0, 1100),
            ("write", "gather_global_root0"): (400.0, 1100),
        },
        # Survives only because Broadcast Completion Time is lower.
        (4, 8): {
            ("write", "broadcast_global"): (400.0, 900),
            ("write", "gather_global_root0"): (500.0, 1100),
        },
    }
    for (vc, depth), cell_metrics in metrics.items():
        for cell in stress_rows:
            bandwidth, completion = cell_metrics.get(cell, (500.0, 900))
            _write_result(
                tmp_path, *cell, 32,
                bandwidth=bandwidth, latency=64.8,
                completion_cycles=completion,
                vc=vc, depth=depth,
                category=f"tradeoff/v{vc}_b{depth}",
            )
    text = pr.report(tmp_path)
    assert "DAT VCs" in text
    assert "Router VC depth = 8 flits/VC" in text
    assert "DAT Router Buffer Capacity (flits/input)" not in text
    assert "NI RX DAT Buffer Capacity (flits/NI)" not in text
    assert "Fixed NI TX DAT entries/NI" not in text
    assert "NI TX DAT depth = 8 entries/NI" in text
    assert "Read RoB depth = 128 beat slots/NI" in text
    assert "Min. Normalized Throughput (%)" in text
    assert "Max. Normalized Completion Time (×)" in text
    assert "Performance Improvement vs Previous Configuration" in text
    assert "Global Multicast Write" in text
    assert "Hierarchical All-to-All" in text
    assert "| DAT configuration | Performance Improvement vs Previous Configuration |" in text
    assert "| 1 VC × 8 flits | Baseline |" in text
    assert "Write: higher Throughput" in text
    assert "Write: lower Completion Time" in text
    assert "Hierarchical A2A" not in text
    assert "每個 workload 與 direction 都是獨立 objective" in text
    assert "Pareto-dominates" in text
    assert "Non-dominated" in text
    assert "Measured non-dominated set" in text
    assert "Overall Pareto" not in text
    assert "Pareto front" not in text
    assert "storage proxy" not in text
    assert "95%" not in text
    assert "量測建議" not in text
    assert "NI capacity screen" not in text


def test_rr_rrd_table_pairs_same_control_case_and_shows_reduction(tmp_path):
    _complete_baseline(tmp_path)
    _complete_channel_compare(tmp_path)
    text = pr.report(tmp_path)
    assert "RR mean Completion Time (cycles/transaction)" in text
    assert "RRD mean Completion Time (cycles/transaction)" in text
    assert "Completion Time reduction (cycles/transaction)" in text
    assert "Completion Time reduction (%)" in text
    assert "| Control Write | 4000.00 | 1000.00 | 3000.00 | 75.0 |" in text
    assert "Pipeline P2P background interval" in text
    assert ("Control Completion Time 從第一次 request `VALID` assertion 開始，到對應的 "
            "B/R handshake 結束") in text


def test_report_level_svgs_cover_main_rows_and_each_pareto_dimension(tmp_path):
    _complete_baseline(tmp_path)
    for vc, depth in (
            (1, 8), (4, 8), (8, 8), (1, 32),
            (2, 16), (2, 32), (4, 16)):
        _complete_tradeoff_config(tmp_path, vc, depth)
    baseline = pr.collect_rows(tmp_path / "baseline")
    tradeoff = pr.collect_rows(tmp_path / "tradeoff")

    paths = pr.write_report_figures(tmp_path, baseline, tradeoff)
    first_render = {path.name: path.read_text(encoding="utf-8") for path in paths}
    pr.write_report_figures(tmp_path, baseline, tradeoff)

    assert {path.name for path in paths} == {
        "ideal_vs_accepted_throughput.svg",
        "hierarchical_alltoall_buffer_tradeoff.svg"}
    assert first_render == {
        path.name: path.read_text(encoding="utf-8") for path in paths}
    for svg in first_render.values():
        assert re.search(r"[\u4e00-\u9fff]", svg) is None

    throughput = first_render["ideal_vs_accepted_throughput.svg"]
    assert throughput.count('class="metric-row"') == 10
    assert "B/cycle" in throughput
    assert "Ideal Bound" in throughput and "Accepted" in throughput
    assert "Global Multicast W" in throughput
    assert "Hierarchical All-to-All R" in throughput

    tradeoff_plot = first_render["hierarchical_alltoall_buffer_tradeoff.svg"]
    assert tradeoff_plot.count('class="panel"') == 2
    assert tradeoff_plot.count('class="candidate-point"') == 16
    assert "DAT Router Buffer Capacity (flits/input)" in tradeoff_plot
    assert ">Write</text>" in tradeoff_plot
    assert ">Read</text>" in tradeoff_plot
    assert ">Throughput (B/cycle)</text>" in tradeoff_plot
    assert 'transform="rotate(-90' in tradeoff_plot
    assert "Non-dominated" in tradeoff_plot and "Dominated" in tradeoff_plot
    assert "Overall Pareto" not in tradeoff_plot


def test_report_embeds_the_report_level_svgs(tmp_path):
    _complete_baseline(tmp_path)
    _complete_tradeoff_config(tmp_path, 1, 8)

    text = pr.report(tmp_path)

    assert "![Ideal and accepted throughput](ideal_vs_accepted_throughput.svg)" in text
    assert "![DUT configuration" not in text
    assert "### DUT Configuration Performance" in text
    assert "Measured / Ideal (Efficiency)" in text
    assert "| Config | Multicast W | Hier. A2A W | Hier. A2A R |" in text
    assert ("| 1 VC × 8 | 400 / 1008 (40%) | 400 / 504 (79%) | "
            "400 / 512 (78%) |") in text
    assert ("![Hierarchical All-to-All buffer trade-off]"
            "(hierarchical_alltoall_buffer_tradeoff.svg)" in text)
    assert "DAT Router Buffer Capacity = DAT VC count × Router VC depth" in text
