import csv
import json

import pytest

import perf_report as pr


_TRAFFIC_COUNTS = {
    "broadcast_row": (4, 16, 4 * 16, 16 * 16, 4),
    "broadcast_col": (4, 16, 4 * 16, 16 * 16, 4),
    "broadcast_submesh": (4, 16, 4 * 16, 16 * 16, 4),
    "broadcast_global": (1, 16, 1 * 16, 16 * 16, 1),
    "gather_global_root0": (15, 1, 15 * 16, 15 * 16, 15),
    "gather_submesh": (12, 4, 12 * 16, 12 * 16, 12),
    "alltoall": (16, 16, 16 * 15 * 16, 16 * 15 * 16, 16),
    "neighbor_exchange": (16, 16, 48 * 16, 48 * 16, 16),
    "pipeline": (15, 15, 15 * 16, 15 * 16, 15),
    "many_to_many": (16, 16, 16 * 4 * 16, 16 * 4 * 16, 16),
}
_BROADCAST_FANOUT = {
    "broadcast_row": 4,
    "broadcast_col": 4,
    "broadcast_submesh": 4,
    "broadcast_global": 16,
}


# Captured from four deterministic 4x4, AxLEN=0, one-round, no-stall runs.
# Keep these dictionaries literal: they are the independent emitted-counter
# oracle for pattern_metrics.ai_resource_flits(), not values generated by it.
_PIPELINE_WRITE_COUNTERS = {
    "dat_0to1": 2, "dat_10to11": 2, "dat_11to15": 2,
    "dat_13to12": 2, "dat_14to13": 2, "dat_15to14": 2,
    "dat_1to2": 2, "dat_2to3": 2, "dat_3to7": 2,
    "dat_4to8": 2, "dat_5to4": 2, "dat_6to5": 2,
    "dat_7to6": 2, "dat_8to9": 2, "dat_9to10": 2,
    "dat_eject_1": 2, "dat_eject_10": 2, "dat_eject_11": 2,
    "dat_eject_12": 2, "dat_eject_13": 2, "dat_eject_14": 2,
    "dat_eject_15": 2, "dat_eject_2": 2, "dat_eject_3": 2,
    "dat_eject_4": 2, "dat_eject_5": 2, "dat_eject_6": 2,
    "dat_eject_7": 2, "dat_eject_8": 2, "dat_eject_9": 2,
    "dat_inject_0": 2, "dat_inject_1": 2, "dat_inject_10": 2,
    "dat_inject_11": 2, "dat_inject_13": 2, "dat_inject_14": 2,
    "dat_inject_15": 2, "dat_inject_2": 2, "dat_inject_3": 2,
    "dat_inject_4": 2, "dat_inject_5": 2, "dat_inject_6": 2,
    "dat_inject_7": 2, "dat_inject_8": 2, "dat_inject_9": 2,
    "rsp_10to9": 1, "rsp_11to10": 1, "rsp_12to13": 1,
    "rsp_13to14": 1, "rsp_14to15": 1, "rsp_15to11": 1,
    "rsp_1to0": 1, "rsp_2to1": 1, "rsp_3to2": 1,
    "rsp_4to5": 1, "rsp_5to6": 1, "rsp_6to7": 1,
    "rsp_7to3": 1, "rsp_8to4": 1, "rsp_9to8": 1,
    "rsp_eject_0": 1, "rsp_eject_1": 1, "rsp_eject_10": 1,
    "rsp_eject_11": 1, "rsp_eject_13": 1, "rsp_eject_14": 1,
    "rsp_eject_15": 1, "rsp_eject_2": 1, "rsp_eject_3": 1,
    "rsp_eject_4": 1, "rsp_eject_5": 1, "rsp_eject_6": 1,
    "rsp_eject_7": 1, "rsp_eject_8": 1, "rsp_eject_9": 1,
    "rsp_inject_1": 1, "rsp_inject_10": 1, "rsp_inject_11": 1,
    "rsp_inject_12": 1, "rsp_inject_13": 1, "rsp_inject_14": 1,
    "rsp_inject_15": 1, "rsp_inject_2": 1, "rsp_inject_3": 1,
    "rsp_inject_4": 1, "rsp_inject_5": 1, "rsp_inject_6": 1,
    "rsp_inject_7": 1, "rsp_inject_8": 1, "rsp_inject_9": 1,
}

_PIPELINE_READ_COUNTERS = {
    "dat_0to1": 1, "dat_10to11": 1, "dat_11to15": 1,
    "dat_13to12": 1, "dat_14to13": 1, "dat_15to14": 1,
    "dat_1to2": 1, "dat_2to3": 1, "dat_3to7": 1,
    "dat_4to8": 1, "dat_5to4": 1, "dat_6to5": 1,
    "dat_7to6": 1, "dat_8to9": 1, "dat_9to10": 1,
    "dat_eject_1": 1, "dat_eject_10": 1, "dat_eject_11": 1,
    "dat_eject_12": 1, "dat_eject_13": 1, "dat_eject_14": 1,
    "dat_eject_15": 1, "dat_eject_2": 1, "dat_eject_3": 1,
    "dat_eject_4": 1, "dat_eject_5": 1, "dat_eject_6": 1,
    "dat_eject_7": 1, "dat_eject_8": 1, "dat_eject_9": 1,
    "dat_inject_0": 1, "dat_inject_1": 1, "dat_inject_10": 1,
    "dat_inject_11": 1, "dat_inject_13": 1, "dat_inject_14": 1,
    "dat_inject_15": 1, "dat_inject_2": 1, "dat_inject_3": 1,
    "dat_inject_4": 1, "dat_inject_5": 1, "dat_inject_6": 1,
    "dat_inject_7": 1, "dat_inject_8": 1, "dat_inject_9": 1,
    "req_10to9": 1, "req_11to10": 1, "req_12to13": 1,
    "req_13to14": 1, "req_14to15": 1, "req_15to11": 1,
    "req_1to0": 1, "req_2to1": 1, "req_3to2": 1,
    "req_4to5": 1, "req_5to6": 1, "req_6to7": 1,
    "req_7to3": 1, "req_8to4": 1, "req_9to8": 1,
    "req_eject_0": 1, "req_eject_1": 1, "req_eject_10": 1,
    "req_eject_11": 1, "req_eject_13": 1, "req_eject_14": 1,
    "req_eject_15": 1, "req_eject_2": 1, "req_eject_3": 1,
    "req_eject_4": 1, "req_eject_5": 1, "req_eject_6": 1,
    "req_eject_7": 1, "req_eject_8": 1, "req_eject_9": 1,
    "req_inject_1": 1, "req_inject_10": 1, "req_inject_11": 1,
    "req_inject_12": 1, "req_inject_13": 1, "req_inject_14": 1,
    "req_inject_15": 1, "req_inject_2": 1, "req_inject_3": 1,
    "req_inject_4": 1, "req_inject_5": 1, "req_inject_6": 1,
    "req_inject_7": 1, "req_inject_8": 1, "req_inject_9": 1,
}

_BROADCAST_HARDWARE_COUNTERS = {
    "dat_0to1": 2, "dat_0to4": 2, "dat_10to14": 2,
    "dat_11to15": 2, "dat_1to2": 2, "dat_1to5": 2,
    "dat_2to3": 2, "dat_2to6": 2, "dat_3to7": 2,
    "dat_4to8": 2, "dat_5to9": 2, "dat_6to10": 2,
    "dat_7to11": 2, "dat_8to12": 2, "dat_9to13": 2,
    "dat_eject_0": 2, "dat_eject_1": 2, "dat_eject_10": 2,
    "dat_eject_11": 2, "dat_eject_12": 2, "dat_eject_13": 2,
    "dat_eject_14": 2, "dat_eject_15": 2, "dat_eject_2": 2,
    "dat_eject_3": 2, "dat_eject_4": 2, "dat_eject_5": 2,
    "dat_eject_6": 2, "dat_eject_7": 2, "dat_eject_8": 2,
    "dat_eject_9": 2, "dat_inject_0": 2,
    "rsp_10to9": 1, "rsp_11to10": 1, "rsp_12to8": 1,
    "rsp_13to12": 1, "rsp_14to13": 1, "rsp_15to14": 1,
    "rsp_1to0": 1, "rsp_2to1": 1, "rsp_3to2": 1,
    "rsp_4to0": 1, "rsp_5to4": 1, "rsp_6to5": 1,
    "rsp_7to6": 1, "rsp_8to4": 1, "rsp_9to8": 1,
    "rsp_eject_0": 1, "rsp_inject_0": 1, "rsp_inject_1": 1,
    "rsp_inject_10": 1, "rsp_inject_11": 1, "rsp_inject_12": 1,
    "rsp_inject_13": 1, "rsp_inject_14": 1, "rsp_inject_15": 1,
    "rsp_inject_2": 1, "rsp_inject_3": 1, "rsp_inject_4": 1,
    "rsp_inject_5": 1, "rsp_inject_6": 1, "rsp_inject_7": 1,
    "rsp_inject_8": 1, "rsp_inject_9": 1,
}

_BROADCAST_REPEATED_UNICAST_COUNTERS = {
    "dat_0to1": 24, "dat_0to4": 6, "dat_10to14": 2,
    "dat_11to15": 2, "dat_1to2": 16, "dat_1to5": 6,
    "dat_2to3": 8, "dat_2to6": 6, "dat_3to7": 6,
    "dat_4to8": 4, "dat_5to9": 4, "dat_6to10": 4,
    "dat_7to11": 4, "dat_8to12": 2, "dat_9to13": 2,
    "dat_eject_1": 2, "dat_eject_10": 2, "dat_eject_11": 2,
    "dat_eject_12": 2, "dat_eject_13": 2, "dat_eject_14": 2,
    "dat_eject_15": 2, "dat_eject_2": 2, "dat_eject_3": 2,
    "dat_eject_4": 2, "dat_eject_5": 2, "dat_eject_6": 2,
    "dat_eject_7": 2, "dat_eject_8": 2, "dat_eject_9": 2,
    "dat_inject_0": 30,
    "rsp_10to9": 2, "rsp_11to10": 1, "rsp_12to8": 4,
    "rsp_13to12": 3, "rsp_14to13": 2, "rsp_15to14": 1,
    "rsp_1to0": 3, "rsp_2to1": 2, "rsp_3to2": 1,
    "rsp_4to0": 12, "rsp_5to4": 3, "rsp_6to5": 2,
    "rsp_7to6": 1, "rsp_8to4": 8, "rsp_9to8": 3,
    "rsp_eject_0": 15,
    "rsp_inject_1": 1, "rsp_inject_10": 1, "rsp_inject_11": 1,
    "rsp_inject_12": 1, "rsp_inject_13": 1, "rsp_inject_14": 1,
    "rsp_inject_15": 1, "rsp_inject_2": 1, "rsp_inject_3": 1,
    "rsp_inject_4": 1, "rsp_inject_5": 1, "rsp_inject_6": 1,
    "rsp_inject_7": 1, "rsp_inject_8": 1, "rsp_inject_9": 1,
}

_EMITTED_COUNTER_FIXTURES = (
    ("directed Write", "pipeline", "write", None, 15, 15,
     _PIPELINE_WRITE_COUNTERS),
    ("directed Read", "pipeline", "read", None, 15, 15,
     _PIPELINE_READ_COUNTERS),
    ("hardware multicast", "broadcast_global", "write", "hardware", 1, 16,
     _BROADCAST_HARDWARE_COUNTERS),
    ("repeated unicast", "broadcast_global", "write", "repeated_unicast", 16, 16,
     _BROADCAST_REPEATED_UNICAST_COUNTERS),
)


def _write_result(root, direction, mapping, outstanding, bandwidth=None,
                   latency=None, vc=2, depth=8, seed=1, category="baseline",
                   r_rob_depth=128, max_txns_per_id=32, burst_beats=64,
                   transactions_per_flow=1, multicast_mode=None,
                   completion_cycles=1000):
    pattern = mapping.split("_", 1)[0]
    if mapping in ("alltoall", "neighbor_exchange", "pipeline", "many_to_many"):
        pattern = mapping
    mode_tag = f"_{multicast_mode}" if multicast_mode else ""
    burst_tag = f"_bl{burst_beats}" if category == "burst" else ""
    run = root / category / f"{mapping}_{direction}_o{outstanding}_s{seed}_v{vc}_b{depth}{mode_tag}"
    run = run.with_name(run.name + burst_tag)
    run.mkdir(parents=True, exist_ok=True)
    bandwidth = bandwidth if bandwidth is not None else 100.0 * min(outstanding, 4)
    latency = latency if latency is not None else 40.0 + outstanding
    producers, consumers, requests, deliveries, initiators = _TRAFFIC_COUNTS[mapping]
    requests *= transactions_per_flow
    deliveries *= transactions_per_flow
    multicast_mode = (multicast_mode or
                      ("hardware" if mapping.startswith("broadcast_") else ""))
    if multicast_mode == "repeated_unicast":
        requests = deliveries
    row = {
        "topology": "mesh_4x4", "vc": str(vc),
        "router_vc_depth": str(depth), "ni_dat_rx_vc_depth": str(depth),
        "pattern": pattern, "traffic_mapping": mapping,
        "measurement_mode": "outstanding", "direction": direction,
        "data_producers": str(producers), "consumers": str(consumers),
        "axi_initiators": str(initiators), "source_requests": str(requests),
        "payload_deliveries": str(deliveries), "rounds": "16",
        "multicast_mode": multicast_mode,
        "destinations_per_source": str(_BROADCAST_FANOUT.get(mapping, "")),
        "transactions_per_flow": str(transactions_per_flow),
        "bytes_per_flow_round": str(burst_beats * transactions_per_flow * 64),
        "source_outstanding_depth": str(outstanding),
        "source_outstanding_hwm": str(outstanding), "seed": str(seed),
        "max_unique_ids": "8", "max_outstanding": "32",
        "r_rob_depth": str(r_rob_depth),
        "max_txns_per_id": str(max_txns_per_id), "ids_per_initiator": "1",
        "burst_length": str(burst_beats - 1), "burst_beats": str(burst_beats),
        "bytes_per_beat": "64", "transaction_bytes": str(burst_beats * 64),
        "completion_cycles": str(completion_cycles),
        "completion_latency_cycles": str(latency),
        "delivered_payload_bytes_per_cycle": str(bandwidth),
        "checker_status": "PASS", "busiest_dat_link_utilization_pct": "80.0",
        "dat_links_total": "48", "dat_links_ge_25_pct": "12",
        "dat_links_ge_50_pct": "8", "dat_links_ge_75_pct": "4",
        "dat_links_ge_90_pct": "0",
        "nmu_read_slot_hwm_beats": str(min(r_rob_depth, outstanding * 64)),
        "nmu_order_list_hwm_transactions": str(min(max_txns_per_id, outstanding)),
    }
    with (run / "result.csv").open("w", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(row))
        writer.writeheader()
        writer.writerow(row)
    mode = multicast_mode or None
    resources = pr.pm.ai_resource_flits(
        mapping, direction, burst_beats, 16 * transactions_per_flow, mode)
    links = [{"name": name, "flit_count": count, "stall_cyc": 0}
             for name, count in resources.items()]
    (run / "perf.json").write_text(json.dumps({"noc": {"links": links}}))
    return run / "result.csv"


def _complete_baseline(root):
    for direction, mappings in (("write", pr.WRITE_MAPPINGS),
                                ("read", pr.READ_MAPPINGS)):
        for mapping in mappings:
            _write_result(root, direction, mapping, 32)


def test_burst_rows_require_fixed_payload_and_fixed_outstanding(tmp_path):
    for burst_beats in (1, 4, 16, 64):
        _write_result(
            tmp_path, "write", "pipeline", 32, category="burst",
            burst_beats=burst_beats, transactions_per_flow=64 // burst_beats)

    rows = pr.collect_burst_rows(tmp_path / "burst")
    assert [(row["burst_beats"], row["transactions_per_flow"])
            for row in rows] == [(1, 64), (4, 16), (16, 4), (64, 1)]
    assert all(row["bytes_per_flow_round"] == 4096 for row in rows)

    for mapping in pr.BURST_MAPPINGS:
        for direction in (("write",) if mapping.startswith("broadcast_")
                          else ("write", "read")):
            if (mapping, direction) == ("pipeline", "write"):
                continue
            for burst_beats in (1, 4, 16, 64):
                _write_result(
                    tmp_path, direction, mapping, 32, category="burst",
                    burst_beats=burst_beats,
                    transactions_per_flow=64 // burst_beats)
    table = pr._burst_table(pr.collect_burst_rows(tmp_path / "burst"))
    assert "Accepted Throughput (B/cycle)" in table
    assert "Delivered throughput" not in table

    path = next((tmp_path / "burst").rglob("result.csv"))
    row = next(csv.DictReader(path.open()))
    row["bytes_per_flow_round"] = "4032"
    with path.open("w", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(row))
        writer.writeheader()
        writer.writerow(row)
    with pytest.raises(SystemExit, match="4096 B/flow/round"):
        pr.collect_burst_rows(tmp_path / "burst")


def test_multicast_comparison_pairs_hardware_and_repeated_unicast(tmp_path):
    results = []
    for mapping in pr.WRITE_MAPPINGS[:4]:
        for mode in ("hardware", "repeated_unicast"):
            path = _write_result(
                tmp_path, "write", mapping, 32,
                category="multicast_compare", multicast_mode=mode)
            results.append((path, 1500 if mode == "repeated_unicast" else 600))
    for path, completion in results:
        row = next(csv.DictReader(path.open()))
        row["completion_cycles"] = str(completion)
        with path.open("w", newline="") as stream:
            writer = csv.DictWriter(stream, fieldnames=list(row))
            writer.writeheader()
            writer.writerow(row)

    rows = pr.collect_multicast_rows(tmp_path / "multicast_compare")
    assert {row["multicast_mode"] for row in rows} == {
        "hardware", "repeated_unicast"}
    assert {(row["mapping"], row["destination_count"])
            for row in rows} == {
                ("broadcast_row", 4), ("broadcast_col", 4),
                ("broadcast_submesh", 4), ("broadcast_global", 16),
            }
    assert next(row for row in rows if row["multicast_mode"] == "hardware")[
        "source_requests"] < 256
    assert next(row for row in rows if row["multicast_mode"] == "repeated_unicast")[
        "source_requests"] == 256

    text = pr._multicast_table(rows)
    assert "Destination Set" in text
    assert "Fanout" in text
    assert "Multicast Injected Flits" in text
    assert "Repeated Unicast Injected Flits" in text
    assert "Completion Time" in text
    assert "Multicast scope" not in text
    assert "Destination count" not in text
    assert "| Global Multicast | 16 | 1040 | 600 | 15600 | 1500 | 2.50 |" in text
    assert "source requests" not in text.lower()
    assert "throughput" not in text.lower()


@pytest.mark.parametrize(("field", "value", "message"), [
    ("payload_deliveries", "239", "payload delivery count"),
    ("source_requests", "239", "source request count"),
])
def test_report_rejects_wrong_workload_counts_before_efficiency(
        tmp_path, field, value, message):
    _complete_baseline(tmp_path)
    path = _write_result(tmp_path, "write", "pipeline", 32)
    row = next(csv.DictReader(path.open()))
    row[field] = value
    with path.open("w", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(row))
        writer.writeheader()
        writer.writerow(row)

    with pytest.raises(SystemExit, match=message):
        pr.collect_rows(tmp_path / "baseline")


def test_report_rejects_wrong_emitted_link_count_before_efficiency(tmp_path):
    _complete_baseline(tmp_path)
    path = _write_result(tmp_path, "write", "pipeline", 32)
    perf_path = path.with_name("perf.json")
    perf = json.loads(perf_path.read_text())
    perf["noc"]["links"][0]["flit_count"] += 1
    perf_path.write_text(json.dumps(perf))

    with pytest.raises(SystemExit, match="resource flit counts"):
        pr.collect_rows(tmp_path / "baseline")


def test_report_rejects_missing_source_injection_before_efficiency(tmp_path):
    path = _write_result(tmp_path, "write", "pipeline", 32)
    perf_path = path.with_name("perf.json")
    perf = json.loads(perf_path.read_text())
    perf["noc"]["links"] = [
        link for link in perf["noc"]["links"] if "_inject_" not in link["name"]
    ]
    perf_path.write_text(json.dumps(perf))

    with pytest.raises(SystemExit, match="resource flit counts"):
        pr.collect_rows(tmp_path / "baseline")


@pytest.mark.parametrize(
    ("label", "mapping", "direction", "mode", "requests", "deliveries", "counters"),
    _EMITTED_COUNTER_FIXTURES,
    ids=[fixture[0] for fixture in _EMITTED_COUNTER_FIXTURES],
)
def test_literal_no_stall_emitted_counters_match_and_reject_corruption(
        tmp_path, label, mapping, direction, mode, requests, deliveries, counters):
    assert pr._expected_workload_counts(mapping, 1, mode) == (requests, deliveries)
    assert any("_inject_" in name for name in counters)
    assert any("to" in name for name in counters)
    assert any("_eject_" in name for name in counters)

    perf_path = tmp_path / f"{label.replace(' ', '_')}.json"
    links = [{"name": name, "flit_count": count, "stall_cyc": 0}
             for name, count in counters.items()]
    perf_path.write_text(json.dumps({"noc": {"links": links}}))
    pr._validate_resource_counters(
        perf_path, mapping, direction, burst_beats=1, rounds=1,
        multicast_mode=mode)

    links[0]["flit_count"] += 1
    perf_path.write_text(json.dumps({"noc": {"links": links}}))
    with pytest.raises(SystemExit, match="resource flit counts"):
        pr._validate_resource_counters(
            perf_path, mapping, direction, burst_beats=1, rounds=1,
            multicast_mode=mode)


@pytest.mark.parametrize(("field", "value"), [
    ("checker_status", "FAIL"), ("transaction_bytes", "2048"),
    ("burst_beats", "32"), ("direction", "mixed"),
    ("source_outstanding_depth", "16"), ("source_outstanding_hwm", "33"),
    ("max_txns_per_id", "16"),
])
def test_collection_rejects_nonfixed_o32_maxid32_rows(tmp_path, field, value):
    path = _write_result(tmp_path, "write", "pipeline", 32)
    row = next(csv.DictReader(path.open()))
    row[field] = value
    with path.open("w", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(row))
        writer.writeheader()
        writer.writerow(row)
    with pytest.raises(SystemExit):
        pr.collect_rows(tmp_path / "baseline")


def test_report_rejects_incomplete_baseline(tmp_path):
    _write_result(tmp_path, "write", "pipeline", 32)
    with pytest.raises(SystemExit, match="incomplete"):
        pr._require_complete(pr.collect_rows(tmp_path / "baseline"))
