`timescale 1ns/1ps

// AUTO-GENERATED by sim/tools/gen_tb_top.py
// Fabric for topology mesh_2x2 (2x2, num_vc=1).
// DO NOT EDIT - modify the generator or sim/topologies/*.yaml instead.
//
// N nodes, each = nmu_wrap + REQ/RSP router_wrap + nsu_wrap, joined by
// inter-router directional links (N/E/S/W). Boundary directions are tied
// off; a tied-off direction DRIVING a valid flit is a $fatal (guards a fabric
// wiring mistake; the C++ route leak is caught by route_compute's abort). The
// DPI ctx handles arrive as ports;
// the fabric does no cmodel_*_create. Each node exposes a master-side AXI
// port (NMU ingress) and a slave-side AXI port (NSU egress).

`ifndef NOC_FABRIC_MESH_2X2_SV
`define NOC_FABRIC_MESH_2X2_SV

module noc_fabric_mesh_2x2 #(
    parameter int unsigned ID_WIDTH              = ni_params_pkg::AXI_ID_WIDTH_DFLT,
    parameter int unsigned ADDR_WIDTH            = ni_params_pkg::AXI_ADDR_WIDTH_DFLT,
    parameter int unsigned DATA_WIDTH            = ni_params_pkg::AXI_DATA_WIDTH_DFLT,
    parameter int unsigned NUM_VC                = 1,
    parameter int unsigned FLIT_WIDTH            = ni_params_pkg::NOC_FLIT_WIDTH_DFLT,
    parameter int unsigned SLAVE_VC_BUFFER_DEPTH = ni_params_pkg::NOC_SLAVE_VC_BUFFER_DEPTH_DFLT
) (
    input  logic clk_i,
    input  logic rst_ni,
    // node0 (x=0, y=0) DPI handles + AXI faces
    input  longint unsigned router0_ctx,
    input  longint unsigned nmu0_ctx,
    input  longint unsigned nsu0_ctx,
    axi4_intf.slave  master_axi_0,   // NMU ingress (driven by tb master)
    axi4_intf.master slave_axi_0,     // NSU egress (consumed by tb slave)
    // node1 (x=1, y=0) DPI handles + AXI faces
    input  longint unsigned router1_ctx,
    input  longint unsigned nmu1_ctx,
    input  longint unsigned nsu1_ctx,
    axi4_intf.slave  master_axi_1,   // NMU ingress (driven by tb master)
    axi4_intf.master slave_axi_1,     // NSU egress (consumed by tb slave)
    // node2 (x=0, y=1) DPI handles + AXI faces
    input  longint unsigned router2_ctx,
    input  longint unsigned nmu2_ctx,
    input  longint unsigned nsu2_ctx,
    axi4_intf.slave  master_axi_2,   // NMU ingress (driven by tb master)
    axi4_intf.master slave_axi_2,     // NSU egress (consumed by tb slave)
    // node3 (x=1, y=1) DPI handles + AXI faces
    input  longint unsigned router3_ctx,
    input  longint unsigned nmu3_ctx,
    input  longint unsigned nsu3_ctx,
    axi4_intf.slave  master_axi_3,   // NMU ingress (driven by tb master)
    axi4_intf.master slave_axi_3     // NSU egress (consumed by tb slave)
);

    localparam int unsigned LINK_PORTS = 5;  // LOCAL + N/E/S/W
    // RouterPort direction indices (router.hpp enum).
    localparam int unsigned RP_LOCAL = 0;
    localparam int unsigned RP_NORTH = 1;
    localparam int unsigned RP_EAST = 2;
    localparam int unsigned RP_SOUTH = 3;
    localparam int unsigned RP_WEST = 4;

    noc_intf #(
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) node0_nmu ();
    noc_intf #(
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) node0_nsu ();
    noc_intf #(
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) node1_nmu ();
    noc_intf #(
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) node1_nsu ();
    noc_intf #(
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) node2_nmu ();
    noc_intf #(
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) node2_nsu ();
    noc_intf #(
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) node3_nmu ();
    noc_intf #(
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) node3_nsu ();

    logic [LINK_PORTS-1:0]   n0_link_req_out_valid,  n0_link_rsp_out_valid;
    logic [FLIT_WIDTH-1:0]   n0_link_req_out_flit   [LINK_PORTS];
    logic [FLIT_WIDTH-1:0]   n0_link_rsp_out_flit   [LINK_PORTS];
    logic [NUM_VC-1:0]       n0_link_req_in_credit  [LINK_PORTS];
    logic [NUM_VC-1:0]       n0_link_rsp_in_credit  [LINK_PORTS];
    logic [LINK_PORTS-1:0]   n0_link_req_in_valid,   n0_link_rsp_in_valid;
    logic [FLIT_WIDTH-1:0]   n0_link_req_in_flit    [LINK_PORTS];
    logic [FLIT_WIDTH-1:0]   n0_link_rsp_in_flit    [LINK_PORTS];
    logic [NUM_VC-1:0]       n0_link_req_out_credit [LINK_PORTS];
    logic [NUM_VC-1:0]       n0_link_rsp_out_credit [LINK_PORTS];

    logic [LINK_PORTS-1:0]   n1_link_req_out_valid,  n1_link_rsp_out_valid;
    logic [FLIT_WIDTH-1:0]   n1_link_req_out_flit   [LINK_PORTS];
    logic [FLIT_WIDTH-1:0]   n1_link_rsp_out_flit   [LINK_PORTS];
    logic [NUM_VC-1:0]       n1_link_req_in_credit  [LINK_PORTS];
    logic [NUM_VC-1:0]       n1_link_rsp_in_credit  [LINK_PORTS];
    logic [LINK_PORTS-1:0]   n1_link_req_in_valid,   n1_link_rsp_in_valid;
    logic [FLIT_WIDTH-1:0]   n1_link_req_in_flit    [LINK_PORTS];
    logic [FLIT_WIDTH-1:0]   n1_link_rsp_in_flit    [LINK_PORTS];
    logic [NUM_VC-1:0]       n1_link_req_out_credit [LINK_PORTS];
    logic [NUM_VC-1:0]       n1_link_rsp_out_credit [LINK_PORTS];

    logic [LINK_PORTS-1:0]   n2_link_req_out_valid,  n2_link_rsp_out_valid;
    logic [FLIT_WIDTH-1:0]   n2_link_req_out_flit   [LINK_PORTS];
    logic [FLIT_WIDTH-1:0]   n2_link_rsp_out_flit   [LINK_PORTS];
    logic [NUM_VC-1:0]       n2_link_req_in_credit  [LINK_PORTS];
    logic [NUM_VC-1:0]       n2_link_rsp_in_credit  [LINK_PORTS];
    logic [LINK_PORTS-1:0]   n2_link_req_in_valid,   n2_link_rsp_in_valid;
    logic [FLIT_WIDTH-1:0]   n2_link_req_in_flit    [LINK_PORTS];
    logic [FLIT_WIDTH-1:0]   n2_link_rsp_in_flit    [LINK_PORTS];
    logic [NUM_VC-1:0]       n2_link_req_out_credit [LINK_PORTS];
    logic [NUM_VC-1:0]       n2_link_rsp_out_credit [LINK_PORTS];

    logic [LINK_PORTS-1:0]   n3_link_req_out_valid,  n3_link_rsp_out_valid;
    logic [FLIT_WIDTH-1:0]   n3_link_req_out_flit   [LINK_PORTS];
    logic [FLIT_WIDTH-1:0]   n3_link_rsp_out_flit   [LINK_PORTS];
    logic [NUM_VC-1:0]       n3_link_req_in_credit  [LINK_PORTS];
    logic [NUM_VC-1:0]       n3_link_rsp_in_credit  [LINK_PORTS];
    logic [LINK_PORTS-1:0]   n3_link_req_in_valid,   n3_link_rsp_in_valid;
    logic [FLIT_WIDTH-1:0]   n3_link_req_in_flit    [LINK_PORTS];
    logic [FLIT_WIDTH-1:0]   n3_link_rsp_in_flit    [LINK_PORTS];
    logic [NUM_VC-1:0]       n3_link_req_out_credit [LINK_PORTS];
    logic [NUM_VC-1:0]       n3_link_rsp_out_credit [LINK_PORTS];

    // -------------------------------------------------------------------------
    // node0 (x=0, y=0): nmu_wrap + router_wrap + nsu_wrap
    // -------------------------------------------------------------------------
    nmu_wrap #(
        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH),
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_nmu_0 (
        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i(nmu0_ctx),
        .axi_i(master_axi_0), .noc_mosi_o(node0_nmu.mosi)
    );

    router_wrap #(
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH),
        .LINK_PORTS(LINK_PORTS)
    ) u_router_0 (
        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i(router0_ctx),
        .noc_nmu_i(node0_nmu.miso),
        .noc_nsu_o(node0_nsu.mosi),
        .link_req_out_valid(n0_link_req_out_valid),
        .link_req_out_flit(n0_link_req_out_flit),
        .link_req_out_credit(n0_link_req_out_credit),
        .link_req_in_valid(n0_link_req_in_valid),
        .link_req_in_flit(n0_link_req_in_flit),
        .link_req_in_credit(n0_link_req_in_credit),
        .link_rsp_out_valid(n0_link_rsp_out_valid),
        .link_rsp_out_flit(n0_link_rsp_out_flit),
        .link_rsp_out_credit(n0_link_rsp_out_credit),
        .link_rsp_in_valid(n0_link_rsp_in_valid),
        .link_rsp_in_flit(n0_link_rsp_in_flit),
        .link_rsp_in_credit(n0_link_rsp_in_credit)
    );

    nsu_wrap #(
        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH),
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_nsu_0 (
        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i(nsu0_ctx),
        .noc_miso_i(node0_nsu.miso), .axi_o(slave_axi_0)
    );

    // -------------------------------------------------------------------------
    // node1 (x=1, y=0): nmu_wrap + router_wrap + nsu_wrap
    // -------------------------------------------------------------------------
    nmu_wrap #(
        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH),
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_nmu_1 (
        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i(nmu1_ctx),
        .axi_i(master_axi_1), .noc_mosi_o(node1_nmu.mosi)
    );

    router_wrap #(
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH),
        .LINK_PORTS(LINK_PORTS)
    ) u_router_1 (
        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i(router1_ctx),
        .noc_nmu_i(node1_nmu.miso),
        .noc_nsu_o(node1_nsu.mosi),
        .link_req_out_valid(n1_link_req_out_valid),
        .link_req_out_flit(n1_link_req_out_flit),
        .link_req_out_credit(n1_link_req_out_credit),
        .link_req_in_valid(n1_link_req_in_valid),
        .link_req_in_flit(n1_link_req_in_flit),
        .link_req_in_credit(n1_link_req_in_credit),
        .link_rsp_out_valid(n1_link_rsp_out_valid),
        .link_rsp_out_flit(n1_link_rsp_out_flit),
        .link_rsp_out_credit(n1_link_rsp_out_credit),
        .link_rsp_in_valid(n1_link_rsp_in_valid),
        .link_rsp_in_flit(n1_link_rsp_in_flit),
        .link_rsp_in_credit(n1_link_rsp_in_credit)
    );

    nsu_wrap #(
        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH),
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_nsu_1 (
        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i(nsu1_ctx),
        .noc_miso_i(node1_nsu.miso), .axi_o(slave_axi_1)
    );

    // -------------------------------------------------------------------------
    // node2 (x=0, y=1): nmu_wrap + router_wrap + nsu_wrap
    // -------------------------------------------------------------------------
    nmu_wrap #(
        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH),
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_nmu_2 (
        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i(nmu2_ctx),
        .axi_i(master_axi_2), .noc_mosi_o(node2_nmu.mosi)
    );

    router_wrap #(
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH),
        .LINK_PORTS(LINK_PORTS)
    ) u_router_2 (
        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i(router2_ctx),
        .noc_nmu_i(node2_nmu.miso),
        .noc_nsu_o(node2_nsu.mosi),
        .link_req_out_valid(n2_link_req_out_valid),
        .link_req_out_flit(n2_link_req_out_flit),
        .link_req_out_credit(n2_link_req_out_credit),
        .link_req_in_valid(n2_link_req_in_valid),
        .link_req_in_flit(n2_link_req_in_flit),
        .link_req_in_credit(n2_link_req_in_credit),
        .link_rsp_out_valid(n2_link_rsp_out_valid),
        .link_rsp_out_flit(n2_link_rsp_out_flit),
        .link_rsp_out_credit(n2_link_rsp_out_credit),
        .link_rsp_in_valid(n2_link_rsp_in_valid),
        .link_rsp_in_flit(n2_link_rsp_in_flit),
        .link_rsp_in_credit(n2_link_rsp_in_credit)
    );

    nsu_wrap #(
        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH),
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_nsu_2 (
        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i(nsu2_ctx),
        .noc_miso_i(node2_nsu.miso), .axi_o(slave_axi_2)
    );

    // -------------------------------------------------------------------------
    // node3 (x=1, y=1): nmu_wrap + router_wrap + nsu_wrap
    // -------------------------------------------------------------------------
    nmu_wrap #(
        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH),
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_nmu_3 (
        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i(nmu3_ctx),
        .axi_i(master_axi_3), .noc_mosi_o(node3_nmu.mosi)
    );

    router_wrap #(
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH),
        .LINK_PORTS(LINK_PORTS)
    ) u_router_3 (
        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i(router3_ctx),
        .noc_nmu_i(node3_nmu.miso),
        .noc_nsu_o(node3_nsu.mosi),
        .link_req_out_valid(n3_link_req_out_valid),
        .link_req_out_flit(n3_link_req_out_flit),
        .link_req_out_credit(n3_link_req_out_credit),
        .link_req_in_valid(n3_link_req_in_valid),
        .link_req_in_flit(n3_link_req_in_flit),
        .link_req_in_credit(n3_link_req_in_credit),
        .link_rsp_out_valid(n3_link_rsp_out_valid),
        .link_rsp_out_flit(n3_link_rsp_out_flit),
        .link_rsp_out_credit(n3_link_rsp_out_credit),
        .link_rsp_in_valid(n3_link_rsp_in_valid),
        .link_rsp_in_flit(n3_link_rsp_in_flit),
        .link_rsp_in_credit(n3_link_rsp_in_credit)
    );

    nsu_wrap #(
        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH),
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_nsu_3 (
        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i(nsu3_ctx),
        .noc_miso_i(node3_nsu.miso), .axi_o(slave_axi_3)
    );

    // -------------------------------------------------------------------------
    // Inter-router link wiring (per direction) + boundary tie-off
    // -------------------------------------------------------------------------
    always_comb begin : link_req_in_n0
        for (int p = 0; p < LINK_PORTS; p++) begin
            n0_link_req_in_valid[p]   = 1'b0;
            n0_link_req_in_flit[p]    = '0;
            n0_link_req_out_credit[p] = '0;
        end
        // NORTH: data IN <- node2 SOUTH OUT; out_credit <- node2 SOUTH in_credit.
        n0_link_req_in_valid[RP_NORTH]   = n2_link_req_out_valid[RP_SOUTH];
        n0_link_req_in_flit[RP_NORTH]    = n2_link_req_out_flit[RP_SOUTH];
        n0_link_req_out_credit[RP_NORTH] = n2_link_req_in_credit[RP_SOUTH];
        // EAST: data IN <- node1 WEST OUT; out_credit <- node1 WEST in_credit.
        n0_link_req_in_valid[RP_EAST]   = n1_link_req_out_valid[RP_WEST];
        n0_link_req_in_flit[RP_EAST]    = n1_link_req_out_flit[RP_WEST];
        n0_link_req_out_credit[RP_EAST] = n1_link_req_in_credit[RP_WEST];
    end

    always_comb begin : link_rsp_in_n0
        for (int p = 0; p < LINK_PORTS; p++) begin
            n0_link_rsp_in_valid[p]   = 1'b0;
            n0_link_rsp_in_flit[p]    = '0;
            n0_link_rsp_out_credit[p] = '0;
        end
        // NORTH: data IN <- node2 SOUTH OUT; out_credit <- node2 SOUTH in_credit.
        n0_link_rsp_in_valid[RP_NORTH]   = n2_link_rsp_out_valid[RP_SOUTH];
        n0_link_rsp_in_flit[RP_NORTH]    = n2_link_rsp_out_flit[RP_SOUTH];
        n0_link_rsp_out_credit[RP_NORTH] = n2_link_rsp_in_credit[RP_SOUTH];
        // EAST: data IN <- node1 WEST OUT; out_credit <- node1 WEST in_credit.
        n0_link_rsp_in_valid[RP_EAST]   = n1_link_rsp_out_valid[RP_WEST];
        n0_link_rsp_in_flit[RP_EAST]    = n1_link_rsp_out_flit[RP_WEST];
        n0_link_rsp_out_credit[RP_EAST] = n1_link_rsp_in_credit[RP_WEST];
    end

    always_comb begin : link_req_in_n1
        for (int p = 0; p < LINK_PORTS; p++) begin
            n1_link_req_in_valid[p]   = 1'b0;
            n1_link_req_in_flit[p]    = '0;
            n1_link_req_out_credit[p] = '0;
        end
        // NORTH: data IN <- node3 SOUTH OUT; out_credit <- node3 SOUTH in_credit.
        n1_link_req_in_valid[RP_NORTH]   = n3_link_req_out_valid[RP_SOUTH];
        n1_link_req_in_flit[RP_NORTH]    = n3_link_req_out_flit[RP_SOUTH];
        n1_link_req_out_credit[RP_NORTH] = n3_link_req_in_credit[RP_SOUTH];
        // WEST: data IN <- node0 EAST OUT; out_credit <- node0 EAST in_credit.
        n1_link_req_in_valid[RP_WEST]   = n0_link_req_out_valid[RP_EAST];
        n1_link_req_in_flit[RP_WEST]    = n0_link_req_out_flit[RP_EAST];
        n1_link_req_out_credit[RP_WEST] = n0_link_req_in_credit[RP_EAST];
    end

    always_comb begin : link_rsp_in_n1
        for (int p = 0; p < LINK_PORTS; p++) begin
            n1_link_rsp_in_valid[p]   = 1'b0;
            n1_link_rsp_in_flit[p]    = '0;
            n1_link_rsp_out_credit[p] = '0;
        end
        // NORTH: data IN <- node3 SOUTH OUT; out_credit <- node3 SOUTH in_credit.
        n1_link_rsp_in_valid[RP_NORTH]   = n3_link_rsp_out_valid[RP_SOUTH];
        n1_link_rsp_in_flit[RP_NORTH]    = n3_link_rsp_out_flit[RP_SOUTH];
        n1_link_rsp_out_credit[RP_NORTH] = n3_link_rsp_in_credit[RP_SOUTH];
        // WEST: data IN <- node0 EAST OUT; out_credit <- node0 EAST in_credit.
        n1_link_rsp_in_valid[RP_WEST]   = n0_link_rsp_out_valid[RP_EAST];
        n1_link_rsp_in_flit[RP_WEST]    = n0_link_rsp_out_flit[RP_EAST];
        n1_link_rsp_out_credit[RP_WEST] = n0_link_rsp_in_credit[RP_EAST];
    end

    always_comb begin : link_req_in_n2
        for (int p = 0; p < LINK_PORTS; p++) begin
            n2_link_req_in_valid[p]   = 1'b0;
            n2_link_req_in_flit[p]    = '0;
            n2_link_req_out_credit[p] = '0;
        end
        // EAST: data IN <- node3 WEST OUT; out_credit <- node3 WEST in_credit.
        n2_link_req_in_valid[RP_EAST]   = n3_link_req_out_valid[RP_WEST];
        n2_link_req_in_flit[RP_EAST]    = n3_link_req_out_flit[RP_WEST];
        n2_link_req_out_credit[RP_EAST] = n3_link_req_in_credit[RP_WEST];
        // SOUTH: data IN <- node0 NORTH OUT; out_credit <- node0 NORTH in_credit.
        n2_link_req_in_valid[RP_SOUTH]   = n0_link_req_out_valid[RP_NORTH];
        n2_link_req_in_flit[RP_SOUTH]    = n0_link_req_out_flit[RP_NORTH];
        n2_link_req_out_credit[RP_SOUTH] = n0_link_req_in_credit[RP_NORTH];
    end

    always_comb begin : link_rsp_in_n2
        for (int p = 0; p < LINK_PORTS; p++) begin
            n2_link_rsp_in_valid[p]   = 1'b0;
            n2_link_rsp_in_flit[p]    = '0;
            n2_link_rsp_out_credit[p] = '0;
        end
        // EAST: data IN <- node3 WEST OUT; out_credit <- node3 WEST in_credit.
        n2_link_rsp_in_valid[RP_EAST]   = n3_link_rsp_out_valid[RP_WEST];
        n2_link_rsp_in_flit[RP_EAST]    = n3_link_rsp_out_flit[RP_WEST];
        n2_link_rsp_out_credit[RP_EAST] = n3_link_rsp_in_credit[RP_WEST];
        // SOUTH: data IN <- node0 NORTH OUT; out_credit <- node0 NORTH in_credit.
        n2_link_rsp_in_valid[RP_SOUTH]   = n0_link_rsp_out_valid[RP_NORTH];
        n2_link_rsp_in_flit[RP_SOUTH]    = n0_link_rsp_out_flit[RP_NORTH];
        n2_link_rsp_out_credit[RP_SOUTH] = n0_link_rsp_in_credit[RP_NORTH];
    end

    always_comb begin : link_req_in_n3
        for (int p = 0; p < LINK_PORTS; p++) begin
            n3_link_req_in_valid[p]   = 1'b0;
            n3_link_req_in_flit[p]    = '0;
            n3_link_req_out_credit[p] = '0;
        end
        // SOUTH: data IN <- node1 NORTH OUT; out_credit <- node1 NORTH in_credit.
        n3_link_req_in_valid[RP_SOUTH]   = n1_link_req_out_valid[RP_NORTH];
        n3_link_req_in_flit[RP_SOUTH]    = n1_link_req_out_flit[RP_NORTH];
        n3_link_req_out_credit[RP_SOUTH] = n1_link_req_in_credit[RP_NORTH];
        // WEST: data IN <- node2 EAST OUT; out_credit <- node2 EAST in_credit.
        n3_link_req_in_valid[RP_WEST]   = n2_link_req_out_valid[RP_EAST];
        n3_link_req_in_flit[RP_WEST]    = n2_link_req_out_flit[RP_EAST];
        n3_link_req_out_credit[RP_WEST] = n2_link_req_in_credit[RP_EAST];
    end

    always_comb begin : link_rsp_in_n3
        for (int p = 0; p < LINK_PORTS; p++) begin
            n3_link_rsp_in_valid[p]   = 1'b0;
            n3_link_rsp_in_flit[p]    = '0;
            n3_link_rsp_out_credit[p] = '0;
        end
        // SOUTH: data IN <- node1 NORTH OUT; out_credit <- node1 NORTH in_credit.
        n3_link_rsp_in_valid[RP_SOUTH]   = n1_link_rsp_out_valid[RP_NORTH];
        n3_link_rsp_in_flit[RP_SOUTH]    = n1_link_rsp_out_flit[RP_NORTH];
        n3_link_rsp_out_credit[RP_SOUTH] = n1_link_rsp_in_credit[RP_NORTH];
        // WEST: data IN <- node2 EAST OUT; out_credit <- node2 EAST in_credit.
        n3_link_rsp_in_valid[RP_WEST]   = n2_link_rsp_out_valid[RP_EAST];
        n3_link_rsp_in_flit[RP_WEST]    = n2_link_rsp_out_flit[RP_EAST];
        n3_link_rsp_out_credit[RP_WEST] = n2_link_rsp_in_credit[RP_EAST];
    end

    // -------------------------------------------------------------------------
    // Boundary tie-off assertion: a boundary direction (no neighbor) must
    // never drive OUT valid. Fires on a fabric wiring mistake; the C++ route
    // leak (dst outside mesh) is caught upstream by route_compute's abort.
    // -------------------------------------------------------------------------
    always_ff @(posedge clk_i) begin
        if (rst_ni) begin
            if (n0_link_req_out_valid[RP_SOUTH])
                $fatal(1, "noc_fabric: node0 drove a flit on tied-off SOUTH (req) - fabric link wiring mistake");
            if (n0_link_rsp_out_valid[RP_SOUTH])
                $fatal(1, "noc_fabric: node0 drove a flit on tied-off SOUTH (rsp) - fabric link wiring mistake");
            if (n0_link_req_out_valid[RP_WEST])
                $fatal(1, "noc_fabric: node0 drove a flit on tied-off WEST (req) - fabric link wiring mistake");
            if (n0_link_rsp_out_valid[RP_WEST])
                $fatal(1, "noc_fabric: node0 drove a flit on tied-off WEST (rsp) - fabric link wiring mistake");
            if (n1_link_req_out_valid[RP_EAST])
                $fatal(1, "noc_fabric: node1 drove a flit on tied-off EAST (req) - fabric link wiring mistake");
            if (n1_link_rsp_out_valid[RP_EAST])
                $fatal(1, "noc_fabric: node1 drove a flit on tied-off EAST (rsp) - fabric link wiring mistake");
            if (n1_link_req_out_valid[RP_SOUTH])
                $fatal(1, "noc_fabric: node1 drove a flit on tied-off SOUTH (req) - fabric link wiring mistake");
            if (n1_link_rsp_out_valid[RP_SOUTH])
                $fatal(1, "noc_fabric: node1 drove a flit on tied-off SOUTH (rsp) - fabric link wiring mistake");
            if (n2_link_req_out_valid[RP_NORTH])
                $fatal(1, "noc_fabric: node2 drove a flit on tied-off NORTH (req) - fabric link wiring mistake");
            if (n2_link_rsp_out_valid[RP_NORTH])
                $fatal(1, "noc_fabric: node2 drove a flit on tied-off NORTH (rsp) - fabric link wiring mistake");
            if (n2_link_req_out_valid[RP_WEST])
                $fatal(1, "noc_fabric: node2 drove a flit on tied-off WEST (req) - fabric link wiring mistake");
            if (n2_link_rsp_out_valid[RP_WEST])
                $fatal(1, "noc_fabric: node2 drove a flit on tied-off WEST (rsp) - fabric link wiring mistake");
            if (n3_link_req_out_valid[RP_NORTH])
                $fatal(1, "noc_fabric: node3 drove a flit on tied-off NORTH (req) - fabric link wiring mistake");
            if (n3_link_rsp_out_valid[RP_NORTH])
                $fatal(1, "noc_fabric: node3 drove a flit on tied-off NORTH (rsp) - fabric link wiring mistake");
            if (n3_link_req_out_valid[RP_EAST])
                $fatal(1, "noc_fabric: node3 drove a flit on tied-off EAST (req) - fabric link wiring mistake");
            if (n3_link_rsp_out_valid[RP_EAST])
                $fatal(1, "noc_fabric: node3 drove a flit on tied-off EAST (rsp) - fabric link wiring mistake");
        end
    end

    // -------------------------------------------------------------------------
    // Inter-router link perf monitors (passive)
    // -------------------------------------------------------------------------
    link_perf_monitor #(
        .LINK_NAME("req_0to2"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_perf_link_req_0_2 (
        .clk_i, .rst_ni,
        .valid(n0_link_req_out_valid[RP_NORTH]),
        .credit_pulse(|n0_link_req_out_credit[RP_NORTH])
    );

    link_perf_monitor #(
        .LINK_NAME("rsp_0to2"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_perf_link_rsp_0_2 (
        .clk_i, .rst_ni,
        .valid(n0_link_rsp_out_valid[RP_NORTH]),
        .credit_pulse(|n0_link_rsp_out_credit[RP_NORTH])
    );

    link_perf_monitor #(
        .LINK_NAME("req_0to1"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_perf_link_req_0_1 (
        .clk_i, .rst_ni,
        .valid(n0_link_req_out_valid[RP_EAST]),
        .credit_pulse(|n0_link_req_out_credit[RP_EAST])
    );

    link_perf_monitor #(
        .LINK_NAME("rsp_0to1"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_perf_link_rsp_0_1 (
        .clk_i, .rst_ni,
        .valid(n0_link_rsp_out_valid[RP_EAST]),
        .credit_pulse(|n0_link_rsp_out_credit[RP_EAST])
    );

    link_perf_monitor #(
        .LINK_NAME("req_1to3"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_perf_link_req_1_3 (
        .clk_i, .rst_ni,
        .valid(n1_link_req_out_valid[RP_NORTH]),
        .credit_pulse(|n1_link_req_out_credit[RP_NORTH])
    );

    link_perf_monitor #(
        .LINK_NAME("rsp_1to3"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_perf_link_rsp_1_3 (
        .clk_i, .rst_ni,
        .valid(n1_link_rsp_out_valid[RP_NORTH]),
        .credit_pulse(|n1_link_rsp_out_credit[RP_NORTH])
    );

    link_perf_monitor #(
        .LINK_NAME("req_1to0"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_perf_link_req_1_0 (
        .clk_i, .rst_ni,
        .valid(n1_link_req_out_valid[RP_WEST]),
        .credit_pulse(|n1_link_req_out_credit[RP_WEST])
    );

    link_perf_monitor #(
        .LINK_NAME("rsp_1to0"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_perf_link_rsp_1_0 (
        .clk_i, .rst_ni,
        .valid(n1_link_rsp_out_valid[RP_WEST]),
        .credit_pulse(|n1_link_rsp_out_credit[RP_WEST])
    );

    link_perf_monitor #(
        .LINK_NAME("req_2to3"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_perf_link_req_2_3 (
        .clk_i, .rst_ni,
        .valid(n2_link_req_out_valid[RP_EAST]),
        .credit_pulse(|n2_link_req_out_credit[RP_EAST])
    );

    link_perf_monitor #(
        .LINK_NAME("rsp_2to3"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_perf_link_rsp_2_3 (
        .clk_i, .rst_ni,
        .valid(n2_link_rsp_out_valid[RP_EAST]),
        .credit_pulse(|n2_link_rsp_out_credit[RP_EAST])
    );

    link_perf_monitor #(
        .LINK_NAME("req_2to0"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_perf_link_req_2_0 (
        .clk_i, .rst_ni,
        .valid(n2_link_req_out_valid[RP_SOUTH]),
        .credit_pulse(|n2_link_req_out_credit[RP_SOUTH])
    );

    link_perf_monitor #(
        .LINK_NAME("rsp_2to0"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_perf_link_rsp_2_0 (
        .clk_i, .rst_ni,
        .valid(n2_link_rsp_out_valid[RP_SOUTH]),
        .credit_pulse(|n2_link_rsp_out_credit[RP_SOUTH])
    );

    link_perf_monitor #(
        .LINK_NAME("req_3to1"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_perf_link_req_3_1 (
        .clk_i, .rst_ni,
        .valid(n3_link_req_out_valid[RP_SOUTH]),
        .credit_pulse(|n3_link_req_out_credit[RP_SOUTH])
    );

    link_perf_monitor #(
        .LINK_NAME("rsp_3to1"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_perf_link_rsp_3_1 (
        .clk_i, .rst_ni,
        .valid(n3_link_rsp_out_valid[RP_SOUTH]),
        .credit_pulse(|n3_link_rsp_out_credit[RP_SOUTH])
    );

    link_perf_monitor #(
        .LINK_NAME("req_3to2"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_perf_link_req_3_2 (
        .clk_i, .rst_ni,
        .valid(n3_link_req_out_valid[RP_WEST]),
        .credit_pulse(|n3_link_req_out_credit[RP_WEST])
    );

    link_perf_monitor #(
        .LINK_NAME("rsp_3to2"), .BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_perf_link_rsp_3_2 (
        .clk_i, .rst_ni,
        .valid(n3_link_rsp_out_valid[RP_WEST]),
        .credit_pulse(|n3_link_rsp_out_credit[RP_WEST])
    );

endmodule

`endif  // NOC_FABRIC_MESH_2X2_SV
