`timescale 1ns/1ps

// AUTO-GENERATED by sim/tools/gen_tb_top.py
// Topology: mesh_2x1  (2x1, num_vc=1)
// DO NOT EDIT - modify the generator or sim/topologies/*.yaml instead.
//
// 2 nodes live inside noc_fabric_mesh_2x1 (NMU + REQ/RSP router + NSU per
// node, joined by directional links). tb_top creates the DPI handles, drives
// each node's master-side AXI with a test master_wrap, ejects each node's
// slave-side AXI with a test slave_wrap, and owns the scoreboard exit logic.
// Variant->instance pairing: master at node k is fed node (k+1)'s coordinate
// scenario, so traffic crosses the fabric to node (k+1) and ejects there.
//
// Self-clocked: clk_i/rst_ni are internal logic (10 ns clock, 4-cycle reset).
// Plusargs +scenario_node0=<path> ... +scenario_node1=<path> kick off the run.

`ifndef TB_TOP_SV
`define TB_TOP_SV

`include "noc_fabric_mesh_2x1.sv"

module tb_top;
    logic clk_i  = 1'b0;
    logic rst_ni = 1'b0;
    always #5 clk_i = ~clk_i;
    initial begin
        repeat (4) @(posedge clk_i);
        rst_ni = 1'b1;
    end
    localparam int unsigned TIMEOUT_CYCLES = 100000;
    initial begin
        repeat (TIMEOUT_CYCLES) @(posedge clk_i);
        $fatal(1, "tb_top: timeout after %0d cycles", TIMEOUT_CYCLES);
    end

    // -------------------------------------------------------------------------
    // Parameters
    // -------------------------------------------------------------------------
    localparam int unsigned ID_WIDTH              = ni_params_pkg::AXI_ID_WIDTH_DFLT;
    localparam int unsigned ADDR_WIDTH            = ni_params_pkg::AXI_ADDR_WIDTH_DFLT;
    localparam int unsigned DATA_WIDTH            = ni_params_pkg::AXI_DATA_WIDTH_DFLT;
    localparam int unsigned NUM_VC                = 1;  // from topology YAML
    localparam int unsigned FLIT_WIDTH            = ni_params_pkg::NOC_FLIT_WIDTH_DFLT;
    localparam int unsigned SLAVE_VC_BUFFER_DEPTH = ni_params_pkg::NOC_SLAVE_VC_BUFFER_DEPTH_DFLT;

    // -------------------------------------------------------------------------
    // DPI lifecycle
    // -------------------------------------------------------------------------
    import "DPI-C" context function void    cmodel_init(input string path);
    import "DPI-C" context function void    cmodel_finalize();
    import "DPI-C" context function int     cmodel_done();
    import "DPI-C" context function int     cmodel_scoreboard_clean();
    import "DPI-C" context function void    cmodel_dump_scoreboard();
    import "DPI-C" context function longint unsigned cmodel_router_create(input string name,
                                                                  input int x_coord, input int y_coord,
                                                                  input int mesh_x_dim, input int mesh_y_dim,
                                                                  input int num_vc);
    import "DPI-C" context function longint unsigned cmodel_master_create(input string name,
                                                                 input string scenario_path);
    import "DPI-C" context function longint unsigned cmodel_slave_create(input string name,
                                                                input string scenario_path);
    import "DPI-C" context function longint unsigned cmodel_nmu_create(input string name,
                                                              input int src_id, input int num_vc);
    import "DPI-C" context function longint unsigned cmodel_nsu_create(input string name,
                                                              input int src_id, input int num_vc);
    import "DPI-C" context function int     cmodel_master_count();
    import "DPI-C" context function int     cmodel_reads_checked();

    string  scn_node0;  // node0 variant (low addr); drives node1.master
    string  scn_node1;  // node1 variant (high addr); drives node0.master
    longint unsigned router0_ctx, m0_ctx, s0_ctx, n0_nmu_ctx, n0_nsu_ctx;
    longint unsigned router1_ctx, m1_ctx, s1_ctx, n1_nmu_ctx, n1_nsu_ctx;

    initial begin
        if (!$value$plusargs("scenario_node0=%s", scn_node0) ||
            !$value$plusargs("scenario_node1=%s", scn_node1)) begin
            $display("ERROR: +scenario_node0=<path> +scenario_node1=<path> required");
            $finish(1);
        end
        cmodel_init(scn_node1);  // shared config; any variant is fine
        router0_ctx = cmodel_router_create("router_0", 0, 0, 2, 1, NUM_VC);
        router1_ctx = cmodel_router_create("router_1", 1, 0, 2, 1, NUM_VC);
        // node0.master -> node1-variant (dst coord 1); ejects at node1.NSU.
        m0_ctx     = cmodel_master_create("master_0", scn_node1);
        s1_ctx     = cmodel_slave_create ("slave_1",  scn_node1);
        n0_nmu_ctx = cmodel_nmu_create("nmu_0", 0, NUM_VC);  // src_id = node0 coord 0
        n0_nsu_ctx = cmodel_nsu_create("nsu_0", 0, NUM_VC);
        // node1.master -> node0-variant (dst coord 0); ejects at node0.NSU.
        m1_ctx     = cmodel_master_create("master_1", scn_node0);
        s0_ctx     = cmodel_slave_create ("slave_0",  scn_node0);
        n1_nmu_ctx = cmodel_nmu_create("nmu_1", 1, NUM_VC);  // src_id = node1 coord 1
        n1_nsu_ctx = cmodel_nsu_create("nsu_1", 1, NUM_VC);
    end

    // -------------------------------------------------------------------------
    // Per-node AXI buses (master-side into the fabric NMU, slave-side out of NSU)
    // -------------------------------------------------------------------------
    axi4_intf #(
        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)
    ) master_nmu_axi_0 ();
    axi4_intf #(
        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)
    ) nsu_slave_axi_0 ();
    axi4_intf #(
        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)
    ) master_nmu_axi_1 ();
    axi4_intf #(
        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)
    ) nsu_slave_axi_1 ();

    // -------------------------------------------------------------------------
    // NoC fabric (2 nodes, directional links)
    // -------------------------------------------------------------------------
    noc_fabric_mesh_2x1 #(
        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH),
        .NUM_VC(NUM_VC), .FLIT_WIDTH(FLIT_WIDTH), .SLAVE_VC_BUFFER_DEPTH(SLAVE_VC_BUFFER_DEPTH)
    ) u_fabric (
        .clk_i(clk_i), .rst_ni(rst_ni),
        .router0_ctx(router0_ctx), .nmu0_ctx(n0_nmu_ctx), .nsu0_ctx(n0_nsu_ctx),
        .master_axi_0(master_nmu_axi_0.slave), .slave_axi_0(nsu_slave_axi_0.master),
        .router1_ctx(router1_ctx), .nmu1_ctx(n1_nmu_ctx), .nsu1_ctx(n1_nsu_ctx),
        .master_axi_1(master_nmu_axi_1.slave), .slave_axi_1(nsu_slave_axi_1.master)
    );

    // -------------------------------------------------------------------------
    // Test endpoints - node0
    // -------------------------------------------------------------------------
    axi_master_wrap #(
        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)
    ) u_master_0 (
        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i(m0_ctx), .axi_o(master_nmu_axi_0.master)
    );

    axi_slave_wrap #(
        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)
    ) u_slave_0 (
        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i(s0_ctx), .axi_i(nsu_slave_axi_0.slave)
    );

    // -------------------------------------------------------------------------
    // Test endpoints - node1
    // -------------------------------------------------------------------------
    axi_master_wrap #(
        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)
    ) u_master_1 (
        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i(m1_ctx), .axi_o(master_nmu_axi_1.master)
    );

    axi_slave_wrap #(
        .ID_WIDTH(ID_WIDTH), .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)
    ) u_slave_1 (
        .clk_i(clk_i), .rst_ni(rst_ni), .ctx_i(s1_ctx), .axi_i(nsu_slave_axi_1.slave)
    );

    // -------------------------------------------------------------------------
    // AXI perf monitors - passive; one per node x {manager, subordinate}
    // -------------------------------------------------------------------------
    axi_perf_monitor #(
        .SLOT_NAME("node0.manager"), .ID_W($bits(master_nmu_axi_0.awid))
    ) u_perf_man_0 (
        .clk_i, .rst_ni,
        .awvalid(master_nmu_axi_0.awvalid), .awready(master_nmu_axi_0.awready),
        .awid(master_nmu_axi_0.awid),       .awaddr(master_nmu_axi_0.awaddr),
        .awlen(master_nmu_axi_0.awlen),     .awsize(master_nmu_axi_0.awsize),
        .wvalid(master_nmu_axi_0.wvalid),   .wready(master_nmu_axi_0.wready),
        .bvalid(master_nmu_axi_0.bvalid),   .bready(master_nmu_axi_0.bready),
        .bid(master_nmu_axi_0.bid),
        .arvalid(master_nmu_axi_0.arvalid), .arready(master_nmu_axi_0.arready),
        .arid(master_nmu_axi_0.arid),       .araddr(master_nmu_axi_0.araddr),
        .arlen(master_nmu_axi_0.arlen),     .arsize(master_nmu_axi_0.arsize),
        .rvalid(master_nmu_axi_0.rvalid),   .rready(master_nmu_axi_0.rready),
        .rlast(master_nmu_axi_0.rlast),     .rid(master_nmu_axi_0.rid)
    );

    axi_perf_monitor #(
        .SLOT_NAME("node0.subordinate"), .ID_W($bits(nsu_slave_axi_0.awid))
    ) u_perf_sub_0 (
        .clk_i, .rst_ni,
        .awvalid(nsu_slave_axi_0.awvalid), .awready(nsu_slave_axi_0.awready),
        .awid(nsu_slave_axi_0.awid),       .awaddr(nsu_slave_axi_0.awaddr),
        .awlen(nsu_slave_axi_0.awlen),     .awsize(nsu_slave_axi_0.awsize),
        .wvalid(nsu_slave_axi_0.wvalid),   .wready(nsu_slave_axi_0.wready),
        .bvalid(nsu_slave_axi_0.bvalid),   .bready(nsu_slave_axi_0.bready),
        .bid(nsu_slave_axi_0.bid),
        .arvalid(nsu_slave_axi_0.arvalid), .arready(nsu_slave_axi_0.arready),
        .arid(nsu_slave_axi_0.arid),       .araddr(nsu_slave_axi_0.araddr),
        .arlen(nsu_slave_axi_0.arlen),     .arsize(nsu_slave_axi_0.arsize),
        .rvalid(nsu_slave_axi_0.rvalid),   .rready(nsu_slave_axi_0.rready),
        .rlast(nsu_slave_axi_0.rlast),     .rid(nsu_slave_axi_0.rid)
    );

    axi_perf_monitor #(
        .SLOT_NAME("node1.manager"), .ID_W($bits(master_nmu_axi_1.awid))
    ) u_perf_man_1 (
        .clk_i, .rst_ni,
        .awvalid(master_nmu_axi_1.awvalid), .awready(master_nmu_axi_1.awready),
        .awid(master_nmu_axi_1.awid),       .awaddr(master_nmu_axi_1.awaddr),
        .awlen(master_nmu_axi_1.awlen),     .awsize(master_nmu_axi_1.awsize),
        .wvalid(master_nmu_axi_1.wvalid),   .wready(master_nmu_axi_1.wready),
        .bvalid(master_nmu_axi_1.bvalid),   .bready(master_nmu_axi_1.bready),
        .bid(master_nmu_axi_1.bid),
        .arvalid(master_nmu_axi_1.arvalid), .arready(master_nmu_axi_1.arready),
        .arid(master_nmu_axi_1.arid),       .araddr(master_nmu_axi_1.araddr),
        .arlen(master_nmu_axi_1.arlen),     .arsize(master_nmu_axi_1.arsize),
        .rvalid(master_nmu_axi_1.rvalid),   .rready(master_nmu_axi_1.rready),
        .rlast(master_nmu_axi_1.rlast),     .rid(master_nmu_axi_1.rid)
    );

    axi_perf_monitor #(
        .SLOT_NAME("node1.subordinate"), .ID_W($bits(nsu_slave_axi_1.awid))
    ) u_perf_sub_1 (
        .clk_i, .rst_ni,
        .awvalid(nsu_slave_axi_1.awvalid), .awready(nsu_slave_axi_1.awready),
        .awid(nsu_slave_axi_1.awid),       .awaddr(nsu_slave_axi_1.awaddr),
        .awlen(nsu_slave_axi_1.awlen),     .awsize(nsu_slave_axi_1.awsize),
        .wvalid(nsu_slave_axi_1.wvalid),   .wready(nsu_slave_axi_1.wready),
        .bvalid(nsu_slave_axi_1.bvalid),   .bready(nsu_slave_axi_1.bready),
        .bid(nsu_slave_axi_1.bid),
        .arvalid(nsu_slave_axi_1.arvalid), .arready(nsu_slave_axi_1.arready),
        .arid(nsu_slave_axi_1.arid),       .araddr(nsu_slave_axi_1.araddr),
        .arlen(nsu_slave_axi_1.arlen),     .arsize(nsu_slave_axi_1.arsize),
        .rvalid(nsu_slave_axi_1.rvalid),   .rready(nsu_slave_axi_1.rready),
        .rlast(nsu_slave_axi_1.rlast),     .rid(nsu_slave_axi_1.rid)
    );

    // -------------------------------------------------------------------------
    // Perf instrumentation - sample every rising edge; dump on final
    // -------------------------------------------------------------------------
    import "DPI-C" context function void cmodel_perf_sample_tick();
    import "DPI-C" context function void cmodel_perf_set_run(input string scenario,
                                                             input longint total_cyc);
    import "DPI-C" context function void cmodel_perf_dump(input string path);

    string        perf_out_path = "perf.json";
    string        perf_scn      = "";
    int unsigned  perf_cycle    = 0;
    initial begin
        void'($value$plusargs("perf_out=%s", perf_out_path));
        void'($value$plusargs("perf_scenario=%s", perf_scn));
    end
    always @(posedge clk_i) begin
        cmodel_perf_sample_tick();
        perf_cycle = perf_cycle + 1;
    end

    final begin
        cmodel_perf_set_run(perf_scn, longint'(perf_cycle));
        cmodel_perf_dump(perf_out_path);
        cmodel_finalize();
    end

    // FSDB waveform dump (VCS only; +define+FSDB_DUMP)
`ifdef FSDB_DUMP
    initial begin
        string fsdb_path;
        if (!$value$plusargs("fsdb=%s", fsdb_path))
            fsdb_path = "dump.fsdb";
        $fsdbDumpfile(fsdb_path);
        $fsdbDumpvars(0, tb_top);
    end
`endif

    // -------------------------------------------------------------------------
    // Exit logic - non-vacuous PASS guard
    // -------------------------------------------------------------------------
    // PASS requires scoreboard clean AND all 2 masters created AND at least
    // one read actually checked (so a write-only / no-op run fails).
    always @(posedge clk_i) begin
        /* verilator lint_off WIDTHTRUNC */
        if (rst_ni && (cmodel_done() != 0)) begin
            if (cmodel_scoreboard_clean() != 0 &&
                cmodel_master_count() == 2 && cmodel_reads_checked() > 0) begin
        /* verilator lint_on WIDTHTRUNC */
                $display("PASS: scenario complete, scoreboard clean");
                cmodel_dump_scoreboard();
                $finish(0);
            end else begin
                $display("FAIL: scoreboard mismatch or vacuous run (masters=%0d reads=%0d)",
                         cmodel_master_count(), cmodel_reads_checked());
                cmodel_dump_scoreboard();
                $fatal(1, "tb_top: run failed");
            end
        end
    end

    // -------------------------------------------------------------------------
    // Centralized DPI error poll
    // -------------------------------------------------------------------------
    import "DPI-C" context function int cmodel_check_error(output string msg);

    always_ff @(posedge clk_i) begin
        /* verilator lint_off WIDTHTRUNC */
        if (rst_ni) begin
            string dpi_err_msg;
            int    dpi_err_code;
            dpi_err_code = cmodel_check_error(dpi_err_msg);
            if (dpi_err_code != 0) begin
                $display("[tb_top] DPI fatal (code=%0d): %s",
                         dpi_err_code, dpi_err_msg);
                cmodel_dump_scoreboard();
                cmodel_finalize();
                $fatal(1, "tb_top: DPI error, simulation aborted");
            end
        end
        /* verilator lint_on WIDTHTRUNC */
    end

endmodule

`endif  // TB_TOP_SV
